### ISSUE TITLE
Extending OntoPiA

### ISSUE THREAD

**Issue by giorgialodi** [italia/daf-ontologie-vocabolari-controllati#1]
Extend the OntoPiA network in order to include domain specific ontologies. Examples that emerge in order to deal with the list of [key datasets](http://elenco-basi-di-dati-chiave.readthedocs.io/it/latest/elencobasidati.html) include (but are not limited to): the ontology for the certified tour guides, the ontology for describing vehicles, etc. You may start the modelling taking into account  ontologies available on the Web,  [ontology design patterns](http://ontologydesignpatterns.org/wiki/Category:ContentOP), and  available open data from dati.gov.it. The proposed ontologies should be part of the network: they should use the others already available and published when dealing with people, organizations, addresses/locations, socialmedia, time, and should use the Level0 top-ontology in order to be federated in the network,

**Comment by vtrgdu** [comment]
Ciao Giorgia, before extending OntoPA, I would complete the top level (Level-0), it seems still quite sketchy ..and by the way: perché dobbiamo parlare inglese?

**Comment by giorgialodi** [comment]
Ciao Guido, 
possiamo sicuramente interloquire in Italiano :-) Quando fu scritto l'issue era  per l'hackathon nazionale in 25 città italiane + San Francisco. Per questo la necessità di usare una lingua che potessero capire tutti. La scelta dell'inglese nelle ontologie è dettata anche per andare oltre i confini nazionali: se le ontologie vengono usate in ambito open data, per esempio, a mio modesto parere dobbiamo pensare in maniera transfrontaliera :-) Label e commenti in italiano sono comunque disponibili. 
Per quanto riguarda invece l'osservazione su L0 Andrea ha risposto in maniera puntuale. Vorremmo tuttavia anche trovare il giusto compromesso tra corretta modellazione e semplicità di utilizzo della stessa, visto che tutte le ontologie della rete saranno tra loro collegate grazie proprio a L0.
Ciao e buona domenica,
Giorgia
P.S.: abbiamo cambiato il nome della rete in OntoPiA :-) Aggiornerò anche i titoli di questi issue!

**Comment by vtrgdu** [comment]
Ciao Giorgia, grazie per la risposta.
Secondo me, più che al trade-off tra correttezza (completezza?) e semplicità, dobbiamo pensare a come gestire la complessità di un task come quello dell'integrazione dei dati della PA (il problema sta lì dai tempi di AIPA - parliamo degli anni '90).
Per esempio: aggiungere una disgiunzione tra Entità e Evento rende più complessa l'ontologia, non tanto in sé (è una riga di codice), ma perché chi la usa non potrà poi introdurre un concetto o un'istanza che sia al tempo stesso Entità e Evento (gli abitanti di Tlön, che nel famoso racconto di Borges rigettavano tale distinzione, andrebbero in crisi). Ma il compito della modellazione concettuale consiste proprio in questo: restringere, mediante opportuni assiomi di significato, le intepretazioni soddisfacenti (modelli) dell'ontologia a quelle 'intese'. Con una disgiunzione del genere saremmo ad esempio tenuti, quando parliamo di 'matrimonio', a chiarire se ci riferiamo all'insieme delle concrete relazioni coniugali (eventi) oppure all'istituzione normata da leggi (oggetto sociale).
Se vogliamo adottare la modellazione concettuale è perché siamo sicuri che questo tipo di distinzioni sia utile. Altrimenti possiamo restare nel vago, mettere i dati così come sono in un cloud e sperare che qualcuno ricostruisca a posteriori, correttamente, le intenzioni di chi li ha prodotti. 
Una issue su GitHub non è - credo - il posto giusto per una discussione metodologica. Spero ci sia modo di affrontare compiutamente il tema, come sai io sono qui per dare una mano :-) 
Per intanto un caro saluto,
Guido

**Comment by giorgialodi** [comment]
@Clou-dia l'origine di questo issue è bello che andato :-) Era per un hackathon specifico. Ovviamente il task di estendere le risorse semantiche qui presenti è un obiettivo generale di schema.gov.it. Io forse chiuderei l'issue e magari rifattorizzando un po' il readme, si può lasciare lì una sezione come contribuire (magari rimandando alla guida che si sta per scrivere).
