### ISSUE TITLE
Far puntare `latest` all'ultima versione usando un symlink

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#104]
## Domanda

Qual è la semantica della cartella `latest` nelle ontologie? Corrisponde al contenuto dell'ultima versione, eg.

```
CPV/latest == CPV/0.7
```

Oppure è una versione ulteriore e successiva (eg. di sviluppo)?
Nel primo caso, avrebbe senso usare un symlink per evitare disallineamenti tra i due contenuti?
Quali impatti ci sarebbero sul delivery attuale di ontopia?

cc: @giorgialodi @anuzzolese @spuliz

**Comment by giorgialodi** [comment]
Latest contiene l'ultima versione dell'ontologia ed è la directory su cui si basa tutto il meccanismo di redirect degli URI attraverso w3id.org. Quindi è directory strategica.  Se l'ultima versione di CPV è la 0.7 in latest ti trovi i contenuti della directory v0.7 di CPV. 
NON è una versione ulteriore e successiva.  
L'impatto di qualunque modifica a latest può comportare problemi per i meccanismi di content-negotiation e di URI dereferentiation. Tutte le directory latest in OntoPiA hanno i contenuti delle ultime versioni di tutte le ontologie (se no i nuovi cambiamenti non sarebbero visibili attraverso software che sono in piedi come Lode e LodView).

**Comment by ioggstream** [comment]
Ok, quindi:

1. la CI dovrebbe intanto verificare che il contenuto di `latest` e di `0.x` siano gli identici;

Una eventuale modifica in questo senso, dovrebbe essere validata sul deployment di ontopia.

**Comment by ioggstream** [comment]
Questo task è sostituito dalla verifica dell'allineamento tra l'ultima versione e latest. #107
