### ISSUE TITLE
Vocabolari: definire il processo di generazione dei RDF e JSONLD dai TURTLE

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#108]
## Mi aspetto

- di definire nella documentazione un processo per generare i file .RDF e JSONLD a partire dai TURTLE
- i file .rdf e jsonld sono comunque committati dagli sviluppatori

**Comment by giorgialodi** [comment]
Cioè? Come fare a salvare un file in un formato invece che un altro? Quando si crea un'ontologia con editor come Protégé hai possibilità di salvare anche in tutte le altre serializzazioni oltre che turtle. Esistono poi anche dei convertitori automatici disponibili via web.

**Comment by ioggstream** [comment]
See https://github.com/perma-id/w3id.org/tree/master/italia

**Comment by giorgialodi** [comment]
@ioggstream possiamo chiudere questo issue? Penso che quanto scritto sopra sia più che sufficiente per creare altre serializzazioni dal turtle.

**Comment by ioggstream** [comment]
@giorgialodi attualmente i file sono generati tramite client application. Dovremmo invece generarli in CI per evitare di dover aggiornare tutte le serializzazioni.
