### ISSUE TITLE
Canonicalizzare file RDF usando https://www.w3.org/TR/xml-exc-c14n/

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#114]
## Mi aspetto

- che gli RDF siano canonicalizzati usando https://www.w3.org/TR/xml-exc-c14n/

**Comment by giorgialodi** [comment]
Non ho capito onestamente e mi sembra ci stiamo ponendo dei problemi che non esistono in pratica. Le serializzazione RDF di ontopia seguono i loro rispettivi standard.

**Comment by ioggstream** [comment]
Se c'è un formato di canonicalizzazione per RDF fai pure sapere. Essendo file generati, senza un meccanismo che permetta di minimizzare i diff tra i file, eventuali bug nei tool di conversione possono portare a file non sintatticamente corretti.

In questo modo invece si semplificano le verifiche anche manuali.

**Comment by giorgialodi** [comment]
Secondo me stiamo dando troppa importanza a questa cosa. Come ti dicevo in OntoPiA abbiamo tutte queste serializzazioni per aumentare la pletora di soggetti che si possono avvicinare: quelli che sono soliti usare XML preferiscono RDF/XML, gli sviluppatori tradizionali che usano JSON, forse capiscono meglio JSON_LD. Però se uno pubblica un turtle, serializzazione tra l'altro più compatta e facilmente leggibile anche da umani, è più che sufficiente :)

**Comment by ioggstream** [comment]
Ok, quindi non è necessario diffare le serializzazioni! Ottimo. Chiudo il tkt.
