### ISSUE TITLE
Attach semantic information to CSV vocabularies

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#118]
## I expect

1. directories with CSV  to contain machine readable semantic information 
2. [1] should allow to generate back the subset of RDF data provided in the CSV

**Comment by ioggstream** [comment]
Consider using frictionless and datapackage.json

**Comment by giorgialodi** [comment]
What do you mean @ioggstream?  The vocs are clearly explained from a semantic perspective. They are simply also available under the CSV format. I do not see the need to do this. Typically you use these elements,where there is no semantic at all.

**Comment by ioggstream** [comment]
I refactored the issue description.

**Comment by giorgialodi** [comment]
I still do not understand the need.  Point 1. directories with CSV to contain machine readable semantic information --> it is already available. There is no specific requirement to do that.

**Comment by ioggstream** [comment]
We need to provide information for mapping CSV back to RDF. We are planning to do this adding a datapackage file to every folder

**Comment by giorgialodi** [comment]
@Clou-dia non mi sembra sia più nei piani di schema una cosa simile, soprattutto alla luce del fatto che i vocabolari usano tutti una sola ontologia e spesso i csv sono ricavati via query sparql dall'RDF. Chiuderei, al massimo si riapre se sorgono necessità future.
