### ISSUE TITLE
Resource URL when rdfs:Literal expected in AtlasOfPaths

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#123]
## I expect 

rdfs:Literal

## Instead

resource URL

https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/AtlasOfPaths/latest/AtlasOfPaths-AP_IT.ttl#L33

**Comment by giorgialodi** [comment]
No @ioggstream this is correct. It is a mechanism to show a UML or graffoo diagram for the ontology. See definition of dct:description "Description may include but is not limited to: an abstract, a table of contents, **a graphical representation**, or a free-text account of the resource"

**Comment by ioggstream** [comment]
Maybe the jena parser expects that this URL is passed as a quoted string, eg "https://....png" and not as a `< ... >` resource?
