### ISSUE TITLE
Idobbligo duplicati in transparency-obligation

### ISSUE THREAD

**Issue by marco-deligios** [italia/daf-ontologie-vocabolari-controllati#129]
nel vocabolario ci sono 3 idobbligo duplicati:

1. **010101** _Obbligo inerente la pubblicazione del Piano triennale per la prevenzione della corruzione e della trasparenza (PTCT)_ essendo presente sia nella sezione **Disposizioni generali** che nella sezione **Altri contenuti** può avere senso
2. **020201** _Obbligo di pubblicazione delle sanzioni per mancata comunicazione dei dati_ riguardando **Organizzazione** e **Personale** mi pare che si tratti di due obblighi diversi
3. **150401** _Obbligo di pubblicazione concernente le liste di attesa_ mi pare che si tratti effettivamente di un doppione

In ogni caso ritengo sarebbe auspicabile disporre di una chiave univoca

**Comment by giorgialodi** [comment]
Ciao @marco-deligios non ho ben capito, Nel mondo semantico tutto ha un id univoco quindi tutti gli obblighi hanno un'URI univoco e persistente che li identificano.010101 è l'id per esempio del primo e contribuisce a definire il suo URI persistente.

Detto questo, non capisco i doppioni. Sul punto 1 scrivi che può aver senso. Sul punto 2 quali due obblighi vedi? Il fatto che è lo stesso che si applica a due settori, indica che quello è l'obbligo poi applicato a diverse cose. Questo è cruciale nel modello semantico anche per evitare duplicazioni di dati.
Sul punto 3 doppione di cosa? 

Scusami ma ti ho seguito poco, sorry :(

**Comment by marco-deligios** [comment]
Hai ragione, stavo guardando la versione csv, ma in rdf non c'è alcuna duplicazione

**Comment by giorgialodi** [comment]
@marco-deligios nei csv se vedi degli obblighi ripetuti è normale non è duplicazione in ogni caso. Se per te va bene, chiuderei questo issue

**Comment by marco-deligios** [comment]
concordo, chiudi pure
