### ISSUE TITLE
Question: Looking for examples

### ISSUE THREAD

**Issue by cristianvasquez** [italia/daf-ontologie-vocabolari-controllati#132]
Hi, I'm looking at the Ontologies in this repo and trying to figure out how to use them. I wonder if some example RDF snippets exemplify how data looks like when using these ontologies. 

I would be grateful if you could provide me with a pointer to examples or presentations about the concrete data.

Cristian.

**Comment by giorgialodi** [comment]
Hi @cristianvasquez it depends on which ontologies you are interested in. Some of them provide examples (e.g., Indicator).  Which one are you looking at?

**Comment by cristianvasquez** [comment]
Hi!, thanks for the response

I was looking at them in general, I remember looking for RDF examples for point of Interest, time, prices, social media... An example can make the ontologies easier to understand and use...

Where can I see the example of Indicator?

**Comment by giorgialodi** [comment]
Hi @cristianvasquez, for instance you can look at example-indicator files here https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/Ontologie/Indicator/latest

**Comment by giorgialodi** [comment]
@cristianvasquez I will close the issue if it is fine for you :)

**Comment by cristianvasquez** [comment]
Sure no problem!
