### ISSUE TITLE
https://w3id.org/italia/onto/CLV misses dct:identifier 

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#153]
## Question

Do we expect dct:identifier in CLV?

Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:path dct:identifier ]
        Focus Node: <https://w3id.org/italia/onto/CLV>
        Result Path: dct:identifier
        Message: Less than 1 values on <https://w3id.org/italia/onto/CLV>->dct:identifier

**Comment by giorgialodi** [comment]
**unfortunately** dct:identifier is mandatory in DCAT-AP_IT (it should be something to remove from my perspective or at least relax in the specification, but at the time being is indeed mandatory). I noticed that actually there is no identifier of CLV. It can be added in this way dct:identifier "https://w3id.org/italia/onto/CLV" ; If you want I can proceed and do it.

**Comment by ioggstream** [comment]
@giorgialodi shouldn't identifier match the latest part of the path? eg.

```
Ontologie/TI/latest/TI-AP_IT.ttl:  dct:identifier "agid" ;
Ontologie/TI/latest/TI-AP_IT.ttl:   dct:identifier "TD" ;
Ontologie/TI/latest/TI-AP_IT.ttl:    dct:identifier "cnr - Z6HZEH - STLab" ;
```

**Comment by giorgialodi** [comment]
For the Agent the identifier is the IPA code. in the case of AGID is ok, in the other cases, since they are not on IPA there is the acronym.

For the identifier of the dataset is a generic string. It can be the URI of the voc. or any other number
