### ISSUE TITLE
Vocabolari: campi mancanti? 

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#158]
```
Message: Less than 1 values on <https://w3id.org/italia/controlled-vocabulary/classifications-for-indicators/indicator-types>->owl:versionInfo
Message: Less than 1 values on <https://w3id.org/italia/controlled-vocabulary/classifications-for-her/erc-panel-h2020-fp>->owl:versionInfo
Message: Less than 1 values on <https://w3id.org/italia/controlled-vocabulary/classifications-for-her/fields-of-research-development>->owl:versionInfo

Message: Less than 1 values on <https://w3id.org/italia/controlled-vocabulary/public-event-types>->ndc:keyConcept
```

**Comment by giorgialodi** [comment]
Per le ontologie la proprietà per la distribuzione è un'altra. Tema che avevamo già messo in evidenza in qualche issue fa con TWs. 
Il dct:identifier secondo me potremmo anche evitarlo ma in teoria essendo un SemanticAsset un Dataset si ereditano le proprietà di dataset che richiede exactly 1 dct:identifier. 

Per CulturalHeritage è più difficile definire hasKeyClass perché CulturalHeritage è solo un wrapper che importa tutta la rete di ontologie del MIC chiamata ArCo. Quindi direi che in questo caso è più difficile da definire le keyClass ed è la ragione per cui non c'è.

L'ontologia DCAT-AP_IT è nata prima di ADMS e aveva dei suoi metadati che sono rimasti quelli. Quindi non trovi gli altri metadati che derivano da ADMS-AP_IT, in sostanza.

In sostanza, molte delle cose che evidenzi qui hanno una ragione ben precisa (anche l'identifier che trovo sia un po' inutile da specificare).

**Comment by ioggstream** [comment]
Quindi:

1- se una ontologia non ha campi adms non li verifico

2- keyClass non è obbligatoria

3- distribution Non obbligatoria per onto

**Comment by ioggstream** [comment]
@giorgialodi fixato, mancano solo questi due campi: 

        Message: Less than 1 values on <https://w3id.org/italia/onto/l0>->admsapit:status
        Message: Less than 1 values on <https://w3id.org/italia/onto/NDC>->admsapit:status

Servono?

per dct:identifier apro un nuovo issue

**Comment by giorgialodi** [comment]
Per status sarebbe utile, ti dice se è draft o meno. In generale, se sono così pochi casi, sia per identifier che per status li possiamo aggiungere.

**Comment by ioggstream** [comment]
@giorgialodi integra status allora su questi e te la mergio subito.

Per dct:identifier faccio un nuovo issue con relativa PR per il validatore: da lì prendiamo i campi da fixare.

**Comment by ioggstream** [comment]
Per ora tolgo status, ma lascio aperto l'issue.

**Comment by giorgialodi** [comment]
@ioggstream penso questi elementi siano stati tutti indirizzati. Chiuderei l'issue
