### ISSUE TITLE
Typo in rdf:type in Subtheme mapping

### ISSUE THREAD

**Issue by cezio** [italia/daf-ontologie-vocabolari-controllati#16]
There's a typo in https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/MappingTema-Sottotema/MappingDataThemeEurovoc.rdf#L370

It's `ConCPet` instead of `ConCEpt`.

**Comment by giorgialodi** [comment]
Thanks @cezio. It should be fine now. Please have a look at it.
