### ISSUE TITLE
Access URLs needs correction

### ISSUE THREAD

**Issue by SrinivasanTarget** [italia/daf-ontologie-vocabolari-controllati#168]
@giorgialodi 
- https://ndc-dev.apps.cloudpub.testedev.istat.it/semantic-assets/details?uri=https%3A%2F%2Fw3id.org%2Fitalia%2Fcontrolled-vocabulary%2Fclassifications-for-public-services%2Fauthentication-type
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-public-services/interactivity-level/interactivity-level.ttl#L212
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-public-services/life-business-event/life-event/life-event.ttl#L222
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-public-services/channel/channel.ttl#L220
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/territorial-classifications/regions/regions.ttl#L230
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-public-services/service-input-output/service-input-output.ttl#L206
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-universities/documents-titulus/documents-titulus.ttl#L139
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-universities/academic-disciplines/academic-disciplines.ttl#L152
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-documents/municipal-notice-board/municipal-notice-board.ttl#L144
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-public-services/life-business-event/business-event/business-event.ttl#L218
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-culture/subject-disciplines/subject-disciplines.ttl#L138
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/theme-subtheme-mapping/theme-subtheme-mapping.ttl#L206
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-organizations/cofog-2009/cofog-2009.ttl#L225
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-organizations/ateco-2007/ateco-2007.ttl
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/classifications-for-routes/route-types/route-types.ttl#L223
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/AtlasOfPaths/latest/AtlasOfPaths-AP_IT.ttl#L1124
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/IoT/latest/IoT-AP_IT.ttl#L928
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/SM/latest/SM-AP_IT.ttl#L1005
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/Transparency/latest/Transparency-AP_IT.ttl#L123
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/COV/latest/COV-AP_IT.ttl#L1557
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/TI/latest/TI-AP_IT.ttl#L664
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/POI/latest/POI-AP_IT.ttl#L598
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/Indicator/latest/Indicator-AP_IT.ttl#L846
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/CLV/latest/CLV-AP_IT.ttl#L1756
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/AccessCondition/latest/AccessCondition-AP_IT.ttl#L494
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/HER/latest/HER-AP_IT.ttl
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/CPV/latest/CPV-AP_IT.ttl#L1194
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/MU/latest/MU-AP_IT.ttl#L399
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/CPEV/latest/CPEV-AP_IT.ttl#L692
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/POT/latest/POT-AP_IT.ttl#L695
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/Cultural-ON/latest/Cultural-ON-AP_IT.ttl#L2399
- https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/ACCO/latest/ACCO-AP_IT.ttl#L919

**Comment by ioggstream** [comment]
fixed in #171

**Comment by giorgialodi** [comment]
@ioggstream can we close this issue?

**Comment by ioggstream** [comment]
thx
