### ISSUE TITLE
Suggerimenti di modifiche minori per luoghi culturali e materie dei servizi pubblici

### ISSUE THREAD

**Issue by danielenole** [italia/daf-ontologie-vocabolari-controllati#177]
**Vocabolario controllato sui luoghi pubblici di interesse culturale**
La voce 'Parco archeologico' si ripete anche sotto 'Centro per la cultura', oltre ad 'Area archeologica' - è una ripetizione? Si può eliminare?

**Vocabolario Controllato sulle Materie dei Servizi Pubblici**
Suggeriamo i seguenti cambi di label, per maggiore chiarezza dei servizi che possono essere classificati in base alla tassonomia:

- Tributi e finanze > Tributi, finanze e contravvenzioni (contravvenzioni è tra le keyword, ma potrebbe non essere intuitiva la label nel caso di utilizzo della tassonomia come navigazione di un sito web istituzionale).
- Attività produttive e commercio > Imprese e commercio (per evitare la confusione con la voce 'Agricoltura', che é fuori da attività produttive e per rispecchiare meglio le keyword proposte, che riguardano tutte temi legati alle imprese)
- Agricoltura > Agricoltura e pesca (per chiarire che in questa voce rientrano anche i servizi legati alla pesca)

**Comment by giorgialodi** [comment]
Ciao @danielenole per il primo punto non mi risulta. Parco archeologico è solo sotto Centro per la cultura non area archeologica. Quindi c'è una sola occorrenza di Parco archeologico.

Per il secondo punto direi che le modifiche sono ragionevoli e si possono apportare facilmente. Chiedo a @ioggstream @mfortini e @spuliz l'ok per procedere.

**Comment by ioggstream** [comment]
@giorgialodi fate pure una pull request e poi vediamo su quella.
Magari coinvolgiamo pure i colleghi di turismo @mfortini ?

**Comment by giorgialodi** [comment]
ma i colleghi del turismo usano il vocabolario sugli argomenti relativi ai servizi pubblici? Il primo commento di @danielenole, forse più pertinente per il turismo, non darà origine a nessuna PR perché quella voce non è ripetuta nel vocabolario. 

Comunque procediamo con le modifiche e facciamo PR.

**Comment by danielenole** [comment]
Ottimo, grazie mille @giorgialodi!
