### ISSUE TITLE
Verificare esistenza URL su github

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#185]
## Mi aspetto

Che gli URL contenuti nei ttl non siano rotti

- [ ] vocabolari deprecati: lasciare o rimuovere?
- [x] broken links

**Comment by ioggstream** [comment]
Vocs-Deprecated @giorgialodi ci servono?

Nel caso vanno corretti gli URL.

 'https://github.com/italia/daf-ontologie-vocabolari-controllati/raw/master/VocabolariControllati/public-event-types/public-event-types-alignment-schemaorg.xlsx'
-> VocabolariControllati/vocs-deprecated/public-event-types/ ...

**Comment by ioggstream** [comment]
Broken links

FAILED test_urls.py::test_url[fpath18-https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/poi-category-classification]
FAILED test_urls.py::test_url[fpath19-https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/poi-category-classification]
FAILED test_urls.py::test_url[fpath20-https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/poi-category-classification]
FAILED test_urls.py::test_url[fpath21-https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/poi-category-classification]
FAILED test_urls.py::test_url[fpath23-https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/VocabolariControllati/poi-category-classification]
FAILED test_urls.py::test_url[fpath91-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-organizations/S13/S13.ttl]
FAILED test_urls.py::test_url[fpath93-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-organizations/S13/S13.rdf]
FAILED test_urls.py::test_url[fpath95-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-organizations/S13/S13.jsonld]
FAILED test_urls.py::test_url[fpath97-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-organizations/S13/S13.csv]
FAILED test_urls.py::test_url[fpath99-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-organizations/S13/S13.xlsx]
FAILED test_urls.py::test_url[fpath142-https://github.com/italia/daf-ontologie-vocabolari-controllati/raw/master/VocabolariControllati/classifications-for-culture/cultural-interest-places/classifications-for-culture/cultural-interest-places.xlsx]
FAILED test_urls.py::test_url[fpath144-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-typology/accommodation-typology.ttl]
FAILED test_urls.py::test_url[fpath146-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-typology/accommodation-typology.rdf]
FAILED test_urls.py::test_url[fpath148-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-typology/accommodation-typology.jsonld]
FAILED test_urls.py::test_url[fpath150-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-typology/accommodation-typology.csv]
FAILED test_urls.py::test_url[fpath152-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-typology/accommodation-typology.xlsx]
FAILED test_urls.py::test_url[fpath154-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-star-rating/accommodation-star-rating.ttl]
FAILED test_urls.py::test_url[fpath156-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-star-rating/accommodation-star-rating.rdf]
FAILED test_urls.py::test_url[fpath158-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-star-rating/accommodation-star-rating.jsonld]
FAILED test_urls.py::test_url[fpath160-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-star-rating/accommodation-star-rating.csv]
FAILED test_urls.py::test_url[fpath162-https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-accommodation-facilities/accommodation-star-rating/accommodation-star-rating.xlsx]

**Comment by giorgialodi** [comment]
> Vocs-Deprecated @giorgialodi ci servono?

No li ho lasciati solo per documentazione.

**Comment by giorgialodi** [comment]
Intendo che non devono finire in schema.gov.it. Per documentazione li possiamo lasciare nel repo.

**Comment by ioggstream** [comment]
@giorgialodi che problemi ci sono se li cancelliamo dal repo? Sarebbero cmq accessibili tramite i tag

**Comment by ioggstream** [comment]
@giorgialodi PTAL. Possiamo rimuovere i vocabolari deprecati?

**Comment by giorgialodi** [comment]
Ce n'è solo uno, se lo vuoi cancellare ok.

**Comment by giorgialodi** [comment]
@Clou-dia riguardando questo issue. C'è solo un vocabolario deprecato. Mi sa che per motivi vari avevo mantenuto comunque una retro compatibilità con i vecchi URI rispetto ai nuovi URI del nuovo vocabolario (il nuovo vocabolario che rimpiazza quello deprecato è cambiato molto rispetto a quello deprecato). Se cancelliamo il vocabolario deprecato perdiamo un minimo di source code da dove derivano certi URI. Se non disturba processi ldi harvesting, e finora è stato così, lascerei stare e chiuderei l'issue.
