### ISSUE TITLE
Missing files: cities.rdf, cities.jsonld

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#190]
## I expect

The files below to exist

-   dcat:downloadURL		<https://raw.githubusercontent.com/italia/daf-ontologie-vocabolari-controllati/master/VocabolariControllati/territorial-classifications/cities/cities.rdf> ;
-    dcat:downloadURL		<https://raw.githubusercontent.com/italia/daf-ontologie-vocabolari-controllati/master/VocabolariControllati/territorial-classifications/cities/cities.jsonld> ;

## Instead

- links seems correct
- only cities.ttl exists

## Notes

To me it is ok to either remove the references to rdf and jsonld and only publish TTL.

**Comment by giorgialodi** [comment]
I think that "the expect" is not really appropriate. When possible we can produce all the possible RDF serialisations. In other cases if there is just one RDF serialisation is ok anyway, in terms of open data for instance.

**Comment by giorgialodi** [comment]
I would suggest to close this issue.

**Comment by ioggstream** [comment]
@giorgialodi if those files are not expected, we should remove the missing downloadURL, right?

**Comment by giorgialodi** [comment]
Ah, oh yes, if they are not defined, it is not correct to include them as distribution of the dataset.
