### ISSUE TITLE
Interoperability requirements: avoid parenthesis in CURIE

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#204]
## I expect

to avoid parenthesis in curie

**Comment by giorgialodi** [comment]
@ioggstream could you please provide an example? Parentheses are used in some URIs of some controlled vocabularies and are fine according to URIs rules.

**Comment by giorgialodi** [comment]
@Clou-dia chiuderei questo issue. Non possiamo cambiare URI consolidati da anni (esempio sulle città, vocabolario critico) soprattutto quando la cosa è anche ammessa (esempio DBPedia le usa).

**Comment by ioggstream** [comment]
@giorgialodi since parentheses can break parsers (e.g. during harvesting), the safe choice is to encode them (e.g., `%28` / `%29` ) when serializing entries.

This does not mean to forbid them.

**Comment by giorgialodi** [comment]
if you want to escape them internally to the harvester (I image you are referring to schema harvester), it is ok since it is an internal technical stuff, but they won't be escaped in actual URIs (in the RDF files I mean).
