### ISSUE TITLE
Errore Bloccante 404 VocabularyDataNotFoundException

### ISSUE THREAD

**Issue by riccafi** [italia/daf-ontologie-vocabolari-controllati#206]
Navigando all'interno del Sito schema.gov.it è possibile provare con lo Swagger le API disponibili per i vocabolari controllati.
A fronte dei vocabolari:  

- ISTAT/education-level
- agid/public-event-types

si ottengono in risposta alle chiamate del tipo:  

- GET https://www.schema.gov.it/api/vocabularies/ISTAT/education-level
- GET https://www.schema.gov.it/api/vocabularies/agid/public-event-types

gli errori:
`{"title":"Unable to find vocabulary data for : istat.education-level","type":"https://www.schema.gov.it/tech/errors/VocabularyDataNotFoundException","status":404,"timestamp":"2023-02-28T12:20:19.624730"}`
e
`{"title":"Unable to find vocabulary data for : agid.public-event-types","type":"https://www.schema.gov.it/tech/errors/VocabularyDataNotFoundException","status":404,"timestamp":"2023-02-28T12:22:12.289443"}`

Ricercando su Internet, risulta da Forum Italia che è comunque un problema generalizzato da almeno il mese di Febbraio 2023.
[Forum Italia](https://forum.italia.it/t/vocabolari-controllati-non-consultabili/32685)

E' stato rilevato il problema ed è in corso la risoluzione?

**Comment by mfortini** [comment]
Grazie mille per la segnalazione. Stiamo investigando il problema e daremo aggiornamenti man mano che lo affrontiamo.

Nel frattempo, suggeriamo di usare le API SPARQL per interrogare i vocabolari controllati.

**Comment by riccafi** [comment]
Grazie, 
ci sono aggiornamenti sulla risoluzione del problema?
I vocabolari controllati interrogabili con SPARQL sono aggiornati?

Grazie mille

**Comment by tizpav** [comment]
Buongiorno, 
mi associo alla richiesta di aggiornamenti sulla risoluzione del problema e per completezza aggiungo che dalle mie verifiche risulta che considerata la lista dei 41 vocabolari ottenuti in GET da https://schema.gov.it/api/vocabularies tutti i vocabolari che hanno href vuoto, ad esempio:
```
		{
			"title": "Vocabolario Controllato delle ripartizioni geografiche d'Italia",
			"description": "Vocabolario controllato delle ripartizioni geografiche d'Italia",
			"agencyId": "istat",
			"keyConcept": "geographical-distribution",
			"links": [
				{
					"href": "",
					"rel": "items",
					"type": "GET"
				}
			]
		},

``` 
restituiscono l'errore 404.

Grazie

**Comment by giorgialodi** [comment]
Gentile @riccafi e @tizpav i due vocabolari segnalati nel primo post non dovrebbero dare più problemi. Sappiamo comunque che ci sono altri vocabolari in schema.gov.it che restituiscono un 404. Abbiamo individuato il problema e anche una possibile soluzione da implementare per superarlo. Tale soluzione è stata inserita nella nostra pipeline di sviluppo e speriamo quanto prima di chiudere definitivamente questo issue. 

@mfortini @bfabio @Clou-dia se volete, ma ditemi voi, lasciamo aperto ancora anche qui questo issue, che comunque è tracciato nei repo di sviluppo software del backend di schema.

**Comment by bfabio** [comment]
@giorgialodi se il problema è nel software e non nei vocabolari di questo repo, allora chiuderei questa issue, ma linkandola alla issue del backend che ne tiene traccia.

**Comment by Clou-dia** [comment]
il problema è stato risolto, sono stati aggiunti i formati csv ai vocabolari che non li avevano e non restituiscono più il 404. vedi [la issue#87]( https://github.com/teamdigitale/dati-semantic-backend/issues/87) 
La issue si può chiudere

**Comment by bfabio** [comment]
@Clou-dia uhm, quella issue linkata però è ancora aperta
