### ISSUE TITLE
Typo in skos:prefLabel della nuova versione vocabolario comuni

### ISSUE THREAD

**Issue by giorgialodi** [italia/daf-ontologie-vocabolari-controllati#223]
Nella nuova versione del  2022-12-31 , in tutte le voci di vocabolario skos:preflabel è scritto con la l minuscola quando in realtà il nome della proprietà in skos è prefLabel con la L maiuscola. Si tratta quindi di rifare il vocabolario controllato correggendo questa proprietà.

**Comment by ioggstream** [comment]
@giorgialodi puoi aprire un issue anche per aggiungere il check al validatore?

:)

**Comment by giorgialodi** [comment]
@ioggstream sì la apro subito
