### ISSUE TITLE
correzione allineamenti CLV

### ISSUE THREAD

**Issue by eliogiu** [italia/daf-ontologie-vocabolari-controllati#238]
In https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/CLV/latest/CLV-aligns-AP_IT.ttl:

sostituire owl:subPropertyOf con: rdfs:subPropertyOf e owl:subClassOf con: rdfs:subClassOf

**Comment by eliogiu** [comment]
Sostituire owl:subClass con: rdfs:subClassOf

**Comment by ioggstream** [comment]
@mfortini I think the PR commit message should match `Fix: #238` to automatically close the issue.  Otherwise, issues should be closed manually.

:) R.

**Comment by giorgialodi** [comment]
Sì questo dovrebbe essere stato risolto con ultimo merge di PR di ISTAT. Chiudo issue

**Comment by eliogiu** [comment]
Avevo dimenticato di segnalare che il problema è presente anche in CLV-aligns-AP_IT.jsonld e CLV-aligns-AP_IT.rdf
