### ISSUE TITLE
Distribuzioni mancanti nei metadati del vocabolario marital-status-types

### ISSUE THREAD

**Issue by giorgialodi** [italia/daf-ontologie-vocabolari-controllati#241]
Il vocabolario dichiara solo una distribuzione in Turtle nel metadato dcat:distribution. 
In realtà il vocabolario è disponibile anche in CSV e RDF/XML. Andrebbero aggiunte anche queste distribuzioni @frisardid @RaffaAracri @RRRoby

**Comment by bfabio** [comment]
Risolta da #271
