### ISSUE TITLE
Directory latest diversa dall'ultima versione in IoT/

### ISSUE THREAD

**Issue by bfabio** [italia/daf-ontologie-vocabolari-controllati#265]
Queste sono le versioni in `IoT`/
```
latest
v0.4
v0.5
v0.6
v0.7
v0.8
v0.9
v1.0
v1.1
v.10
```

Le directory `latest` e `v.10` sono diverse, ma `latest` e `v1.1` sono uguali.

Direi che quel `v.10` è un refuso e dovrebbe chiamarsi `v0.10`, anche considerato che altrimenti sarebbe un bel salto di versioni, da 1.1 a 10

Ti torna @giorgialodi?

**Comment by giorgialodi** [comment]
Torna torna :)
