### ISSUE TITLE
indicazione errata vocabolario delle licenze per proprietà referenceDoc della BCS license

### ISSUE THREAD

**Issue by giorgialodi** [italia/daf-ontologie-vocabolari-controllati#276]
La proprietà referenceDoc del vocabolario sulle licenze indica della documentazione di riferimento per la licenza che si descrive NON l'URI della licenza stessa. 
@tmancinelli bisognerebbe modificare il valore di quella proprietà per la licenza BCS, sostituendo quello attuale con un link al testo della licenza.

@Clou-dia @mfortini

**Comment by icdpgithub** [comment]
Buon pomeriggio @giorgialodi, grazie del commento.
Innanzitutto si segnala che il seguente account “icdpgithub”, account ufficiale della Digital Library, da questo momento in avanti dovrà essere messo al corrente, valutare e approvare tutte le proposte di revisione/modifica da parte di utenti terzi dei contenuti delle pagine promosse dalla Digital Library.
Di seguito si fornisce l’URL della documentazione di riferimento per la licenza BCS: https://docs.italia.it/italia/icdp/icdp-pnd-circolazione-riuso-docs/it/v1.0-giugno-2022/testo-etichetta-BCS.html
Si segnala inoltre che l’URI della licenza non è corretto: https://schema.gov.it/lodview/controlled-vocabulary/licenses/B117_BSC10 deve essere corretto in https://schema.gov.it/lodview/controlled-vocabulary/licenses/B117_BCS (la licenza si chiama “Beni Culturali Standard”, da cui l’acronimo “BCS”, e non è soggetta a versionamento, trattandosi di una dichiarazione sui diritti che riassume le possibilità di uso/riuso delle riproduzioni digitali di opere pubbliche in pubblico dominio)
Scriviamo questo messaggio a seguito di una riunione con @giorgialodi. Chiederemmo gentilmente un vostro supporto per effettuare la modifica dell’URI della licenza, delegando a @giorgialodi il compito.
Grazie! Attendiamo un vostro aggiornamento.
@giorgialodi  @mfortini @Clou-dia

**Comment by icdpgithub** [comment]
Buongiorno @giorgialodi @mfortini @Clou-dia - avete aggiornamenti rispetto al nostro precedente commento?
Avremmo necessità di effettuare l'aggiornamento della URI il prima possibile per rispondere alle stringenti tempistiche del progetto PNRR.
Grazie

**Comment by giorgialodi** [comment]
Buongiorno @icdpgithub proviamo a farlo entro questa settimana. Grazie.

**Comment by giorgialodi** [comment]
> Buon pomeriggio @giorgialodi @mfortini @Clou-dia - potete aggiornarci rispetto all'attività? Grazie

In corso.

**Comment by icdpgithub** [comment]
@giorgialodi abbiamo visto attività (cod. Bug fixing #281). Ci sono novità?
@Clou-dia @mfortini 
Grazie

**Comment by Clou-dia** [comment]
Buongiorno, le modifiche sono state apportate revisionate e applicate. Ora attendiamo una data da ISTAT per l’harvesting in produzione, così da applicare le modifiche anche a catalogo schema.gov.it

**Comment by icdpgithub** [comment]
Ciao @Clou-dia. Ci sono novità? 
@giorgialodi @mfortini 
Grazie

**Comment by Clou-dia** [comment]
@icdpgithub ISTAT ha pianificato il prossimo harvesting in produzione è pianificato per il 16/10. 
Saluti

**Comment by Clou-dia** [comment]
Buongiorno, l'harvesting è andato a buon fine, chiudiamo la issue
