### ISSUE TITLE
Problema su Vocabolario Controllato dei Comuni d'Italia

### ISSUE THREAD

**Issue by Riccardo644** [italia/daf-ontologie-vocabolari-controllati#277]
Mi sono accorto che su alcune comuni non sono associati correttamente alla provincia, (es. Torino) che dovrebbe essere 001, ha si molti comuni associati a 001, ma quelli che hanno end date 9999-12-31, sono stati spostati al id 201 senza nessun motivo, fin qualche giorno fa funzionava tutto correttamente.

esempio:

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        PREFIX clvapit: <https://w3id.org/italia/onto/CLV/>
        PREFIX ti: <https://w3id.org/italia/onto/TI/>
        

        SELECT ?city ?cityLabel ?startTime ?endTime WHERE {
            ?city skos:broader <https://w3id.org/italia/controlled-vocabulary/territorial-classifications/provinces/201> .
            ?city rdfs:label ?cityLabel .
      
        OPTIONAL { 
        ?city clvapit:hasSOValidity ?interval .
        ?interval ti:startTime ?startTime .
        OPTIONAL { ?interval ti:endTime ?endTime }
         }
        
        }
      
    ORDER BY ?cityLabel
    
    se fate questa query con 001 non viene nessun comunue con data finale 9999-12-31, se usate 201 che non è riferito a nulla vi escono tutti

**Comment by Clou-dia** [comment]
Ciao @Riccardo644, 
grazie per la segnalazione verifichiamo, ci sono state delle modifiche il 12/07

**Comment by Clou-dia** [comment]
@RRRoby potreste verificare

**Comment by Riccardo644** [comment]
qualche update?

**Comment by RRRoby** [comment]
Salve,
è pronta la PR di ripristino dei codici di provincia ante 2015 su tutto il vocabolario.
Il problema riscontrato è relativo al fatto che il codice delle città metropolitane ha sostituito il codice delle province dal 1 gennaio 2015.
Ad esempio Torino aveva come codice provincia 001 prima del 2015 quando è passata a città metropolitana ha assunto la codifica 201.
Questa seconda codifica verrà introdotta nella prossima versione del vocabolario.



----- Messaggio originale -----
Da: "Riccardo644" ***@***.***>
A: "italia/daf-ontologie-vocabolari-controllati" ***@***.***>
Cc: "RRRoby" ***@***.***>, "Mention" ***@***.***>
Inviato: Lunedì, 29 luglio 2024 11:23:14
Oggetto: Re: [italia/daf-ontologie-vocabolari-controllati] Problema su Vocabolario Controllato dei Comuni d'Italia (Issue #277)

qualche update?


-- 
Reply to this email directly or view it on GitHub:
 https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fdaf-ontologie-vocabolari-controllati%2Fissues%2F277%23issuecomment-2255430016&e=2637b01d&h=6be16d7c&f=y&p=y

**Comment by Riccardo644** [comment]
quindi cosa si deve utilizzare ora come ora non ho capito

**Comment by RRRoby** [comment]
quello che hai sempre utilizzato non ti crea problemi perchè nel vocabolario delle province il codice provincia è messo in relazione con il codice delle città metropolitane.
In alcuni dataset non viene più usata la codifica delle province ante 2015 ma direttamente quella della città metropolitana, 
quindi se utilizza il vocabolario cities per fare anche record linkage potresti non agganciare i dati riferiti alle città metropolitane ma risolvi utilizzando il vocabolario delle province.


----- Messaggio originale -----
Da: "Riccardo644" ***@***.***>
A: "italia/daf-ontologie-vocabolari-controllati" ***@***.***>
Cc: "RRRoby" ***@***.***>, "Mention" ***@***.***>
Inviato: Lunedì, 29 luglio 2024 12:21:58
Oggetto: Re: [italia/daf-ontologie-vocabolari-controllati] Problema su Vocabolario Controllato dei Comuni d'Italia (Issue #277)

quindi cosa si deve utilizzare ora come ora non ho capito

-- 
Reply to this email directly or view it on GitHub:
 https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fdaf-ontologie-vocabolari-controllati%2Fissues%2F277%23issuecomment-2255552868&e=2637b01d&h=97cbe5d4&f=y&p=y

**Comment by Riccardo644** [comment]
Non mi sembra risolto faccio questa e non mi ritorna nulla, 20 giorni fa funzionava, su cosa devo basarmi ce cambiano casualmente?

 SELECT ?city ?cityLabel ?startTime ?endTime WHERE {
        ?city skos:broader <https://w3id.org/italia/controlled-vocabulary/territorial-classifications/provinces/001> .
        ?city rdfs:label ?cityLabel .
  
    OPTIONAL { 
    ?city clvapit:hasSOValidity ?interval .
    ?interval ti:startTime ?startTime .
    OPTIONAL { ?interval ti:endTime ?endTime }
     }
    
    }
  
ORDER BY ?cityLabel

**Comment by RRRoby** [comment]
Non è stato ancora fatto l'harvesting che ricarica tutti gli aggiornamenti dei singoli file su https://github.com/italia/daf-ontologie-vocabolari-controllati/  attraverso una operazione di indicizzazione sul repository (Virtuoso) di "Schema" su cui viene eseguita la query SPARQL.
Appena disponibili sarà mia cura avvisarla.

Con la nuova versione la query con il valore 201 non recupera nessun dato mentre con 001 tutti i comuni di Torino

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX clvapit: <https://w3id.org/italia/onto/CLV/>
PREFIX ti: <https://w3id.org/italia/onto/TI/>
 
SELECT ?city ?cityLabel ?startTime ?endTime WHERE {
        ?city skos:broader <https://w3id.org/italia/controlled-vocabulary/territorial-classifications/provinces/201> .
        ?city rdfs:label ?cityLabel .
    OPTIONAL { 
    ?city clvapit:hasSOValidity ?interval .
    ?interval ti:startTime ?startTime .
    OPTIONAL { ?interval ti:endTime ?endTime }
     }
    }
ORDER BY ?cityLabel







----- Messaggio originale -----
Da: "Riccardo644" ***@***.***>
A: "italia/daf-ontologie-vocabolari-controllati" ***@***.***>
Cc: "RRRoby" ***@***.***>, "Mention" ***@***.***>
Inviato: Lunedì, 29 luglio 2024 12:42:14
Oggetto: Re: [italia/daf-ontologie-vocabolari-controllati] Problema su Vocabolario Controllato dei Comuni d'Italia (Issue #277)

Non mi sembra risolto faccio questa e non mi ritorna nulla, 20 giorni fa funzionava, su cosa devo basarmi ce cambiano casualmente?

 SELECT ?city ?cityLabel ?startTime ?endTime WHERE {
        ?city skos:broader < https://urlsand.esvalabs.com/?u=https%3A%2F%2Fw3id.org%2Fitalia%2Fcontrolled-vocabulary%2Fterritorial-classifications%2Fprovinces%2F001&e=2637b01d&h=ac23ca2f&f=y&p=y > .
        ?city rdfs:label ?cityLabel .
  
    OPTIONAL { 
    ?city clvapit:hasSOValidity ?interval .
    ?interval ti:startTime ?startTime .
    OPTIONAL { ?interval ti:endTime ?endTime }
     }
    
    }
  
ORDER BY ?cityLabel



-- 
Reply to this email directly or view it on GitHub:
 https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fdaf-ontologie-vocabolari-controllati%2Fissues%2F277%23issuecomment-2255590986&e=2637b01d&h=94233d11&f=y&p=y

**Comment by Riccardo644** [comment]
ok  e per quando è prevista questa nuova versione che permetterà di prendere tutti i comuni di torino con 001? come è sempre stato, inoltre torino non è l'unico che ha questo problema:
anche milano per esempio

**Comment by frisardid** [comment]
Sono stati ripristinate le URI con i codici delle province ante 2015 per le città metropolitane (Cagliari, Catania, Messina, Palermo, Reggio Calabria, Bari, Napoli, Roma, Firenze, Bologna, Venezia, Milano, Genova, Torino).

**Comment by Riccardo644** [comment]
sembra bene grazie
