### ISSUE TITLE
Alcune note su Istat-Classificazione-08-Territorio

### ISSUE THREAD

**Issue by aborruso** [italia/daf-ontologie-vocabolari-controllati#3]
Buongiorno,
per il CSV pubblicato [qui](https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/ClassificazioneTerritorio) farei le seguenti cose:

- specificherei encoding e separatore;
- in ogni caso lo pubblicherei in UTF-8 con la `,` come separatore;
- nel campo `Popolazione legale 2011 (09/10/2011)`, c'è da rimuovere nei valori il carattere `.`.

Allego un output di esempio, con i tre punti come sopra.

Saluti

[Istat-Classificazione-08-Territorio_out.zip](https://github.com/italia/daf-ontologie-vocabolari-controllati/files/1387013/Istat-Classificazione-08-Territorio_out.zip)

**Comment by aborruso** [comment]
Aggiungo che nel campo `Progressivo del Comune (2)` ci sono due spazi (a inizio e fine) da rimuovere.

![image](https://user-images.githubusercontent.com/30607/31757522-98bab9d8-b4a9-11e7-9691-fea65d622de5.png)

**Comment by giorgialodi** [comment]
Ciao @aborruso grazie per la segnalazione. A onor del vero il CSV viene da ISTAT stesso; qui è stato pubblicato per indicare che la versione RDF, allineata all'ontologia dei luoghi/indirizzi, è nata a partire da quel CSV. Pertanto, da questo tuo commento è bene:
- specificare un po' meglio questa cosa; 
- indicare anche alla fonte queste segnalazioni giustissime;
Poi verifichiamo anche nell'ambito DAF dove queste classificazioni ufficiali sono "Ingestionate".

**Comment by giorgialodi** [comment]
@aborruso ho riprodotto il CSV correggendo gli spazi segnalati. La codifica dovrebbe essere corretta e ogni valore è separato da virgola. Ho dato queste indicazioni nel readme del repo perché ho applicato il tutto a tutti gli altri csv dei vocabolari controllati presenti. Dovrebbe essere tutto ok ora. 
Solo una  cosa: non ho ben capito il commento sul campo "popolazione legale 2011). Non ho trovato ".". 
Rimane sempre l'alert sul fatto che questo csv è prodotto da ISTAT e qui noi l'abbiamo caricato  per verificarlo rispetto alla versione RDF/Turtle (allineata con l'ontologia CLV-AP_IT - Core Location Vocabulary - Italian Application Profile). Avrò cura di segnalare queste cose ai tecnici che se ne occupano.

**Comment by aborruso** [comment]
@giorgialodi nella [versione precedente](https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/0b6a1f4fae35db7b6df1ee9401118024e5d56821/VocabolariControllati/ClassificazioneTerritorio/Istat-Classificazione-08-Territorio.csv) del CSV, è presente il carattere `.` (vedi sotto). Probabilmente il tuo cleaning lo ha rimosso in automatico.

Ti ringrazio per la segnalazione in ISTAT. 

![image](https://user-images.githubusercontent.com/30607/32691610-af77ae88-c70a-11e7-82d7-815642a59f93.png)
