### ISSUE TITLE
Cultural-ON, issues with defintions for `name` and `altLabel`

### ISSUE THREAD

**Issue by marco-brandizi** [italia/daf-ontologie-vocabolari-controllati#30]
Hi all, 

reporting my recent experience here, as I was suggested to do.

In CulturalON, there is the name property, which has this definition attached:

_Property used to associate a name with an event and a project_

So, the property has a generic name, but it's supposed to be used for a specific domain (which, by the way, is not formalised via rdfs:domain). That's not very good, probably you don't need such a specific name and actually you intend name as the usual generic name (and you might as well use some existing property like that, like schema:name, but I understand the philosophy of these ontologies is to have a local vocabulary to be mapped outside).

Second issue, name has a subproperty altLabel. In common practice, names and labels are not the same thing, names are more similar to identifiers, tend to be used more by technical personnel, don't depend on a language, while labels are for display purpose and might have multiple translations. Moreover, altLabel has the following Italian definition:

_nome alternativo dell'istituto e luogo della cultura_ (alt name for the institute or cultural place)

This is different than the English definition (generically says 'alternative label') and contradicts the definition of the parent property.

Moreover, the rdfs:domain of altName is NameInTime. I understand the need for composed/reified names like NameInTime, but I don't see the need to constraint altName to that class only. 

My best guess is that these definitions were merged from initial drafts, developed separately, and now they still need review. I'm also guessing that what you actually want is to have them as primary name and alt name, without (domain) restrictions to any particular nameable entity.

**Comment by giorgialodi** [comment]
Hi @marco-brandizi, we are currently acting on the ontology. We corrected this issue. When the overall refactoring of Cultural-ON for OntoPiA is completed (probably in a few days), the correction will enter into force. Thanks for your support.

**Comment by giorgialodi** [comment]
@marco-brandizi a new version of cultural-on ontology has been published this morning. We took into account your observations and correct the property.
