### ISSUE TITLE
Label italiana ultima_data_validazione_codice_fiscale

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#31]
## Potrebbe aver senso
@giorgialodi 
Limitare le `label` a 4 parole, come fatto per la dizione inglese.

https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/b120fb5b653985b3dee2aa8aed5ec4340bff8568/Ontologie/COV/latest/COV-AP_IT.jsonld#L3018

**Comment by giorgialodi** [comment]
Eh ma la dizione inglese è compatta per definizione. In IPA c'è stessa dicitura ma codice fiscale è scritto "c.f." come abbreviazione. Potremmo mettere "ultima data validazione cf" e sono quattro ma la label di solito serve per la leggibilità degli utenti e così è meno leggibile di quanto attualmente presente. Hai proposte? Che problemi ti causa?

**Comment by ioggstream** [comment]
L'idea attuale è questa:

  - se vuoi serializzare un oggetto in inglese, usi il nome del campo dell'ontologia
  - se vuoi serializzare un oggetto in italiano, usi il nome della label.

Per la maggior parte dei campi, la label è abbastanza semplice. Con label più lunghe ovviamente il gioco si complica. In questo caso la entry "normalizzata" in iPA come questa
{
"codice_fiscale": "...",
"ultima_data_validazione_codice_fiscale": '2018-01-01'
}
potrebbe tentare qualcuno di usare un'altra dizione e/o abbreviare impropriamente il campo.

Una soluzione potrebbe essere che, quando definite l'ontologia, indicate un'analogo "italiano" per il nome del campo.

**Comment by giorgialodi** [comment]
ma quando dici un analogo "italiano" per il nome del campo intendi un URI in italiano o un'annotazione che dica "puoi usare un nome di proprietà in italiano abbrevviato tipo "ultima_data_val_cf"?

**Comment by giorgialodi** [comment]
@ioggstream ciao, ritorno su questo issue. Se per te va bene, oltre all'attuale label in italiano io aggiungerei all'ontologia, solo per questo caso, un alternative label (sempre in ITA) che è "ultima_validazione_cf" ovviamente è una data perché il tipo è data, cf è abbreviazione abbastanza nota che se usata insieme alla proprietà "codice fiscale" come mi hai fatto vedere sopra fa intuire che stiamo parlando di quello. Con questa soluzione abbiamo sicuramente una label più compatta (tuo requisito), andiamo in aggiunta a una label più lunga e chiara e quindi garantiamo allo stesso tempo leggibilità (nostro requisito). Che ne pensi?

**Comment by ioggstream** [comment]
@giorgialodi per me anche `ultima_validazione_codice_fiscale` potrebbe andare.

**Comment by giorgialodi** [comment]
@ioggstream se per te va bene ultima_validazione_codice_fiscale procederei con il cambio con questa label. In ogni caso l'URI è parlante e il tipo è parlante uguale :) Appena fatto chiudo l'issue.
