### ISSUE TITLE
Refuso in eInvoiceServiceStartingDate

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#32]
## Mi aspetto
@giorgialodi 
Una `label` che descriva il servizio, eg. `Data di inizio fatturazione elettronica` 

## Invece

Ho una label con un refuso:  `Data avivo servizio`

https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/b120fb5b653985b3dee2aa8aed5ec4340bff8568/Ontologie/COV/latest/COV-AP_IT.jsonld#L258

**Comment by giorgialodi** [comment]
@ioggstream ok controllo e agisco

**Comment by giorgialodi** [comment]
@ioggstream è già stato corretto, almeno a me risulta corretto. Ricontrolla anche tu nell'ultima versione ora pubblicata
