### ISSUE TITLE
typo in CLV-AP_IT

### ISSUE THREAD

**Issue by seralf** [italia/daf-ontologie-vocabolari-controllati#4]
There is a typo using `tiapit` in place of `clvapit` in `CLV-AP_IT` ontology:
https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/IndirizziLuoghi/latest/CLV-AP_IT.ttl#L12-L14

**Comment by seralf** [comment]
fixed in: https://github.com/italia/daf-ontologie-vocabolari-controllati/pull/5

**Comment by giorgialodi** [comment]
merged and fixed the typo in version 0.7 (which is the latest) and in the different formats of the same ontology (i.e., RDF/XML and JSON-LD).
