### ISSUE TITLE
Proposta vocabolario controllato del titolario di classificazione degli archivi delle Università

### ISSUE THREAD

**Issue by gpirrotta** [italia/daf-ontologie-vocabolari-controllati#47]
Il titolario di classificazione, secondo la legge italiana, è uno strumento dell'archivio corrente, che serve per dividere la documentazione prodotta o ricevuta da un soggetto in settori e categorie, schematizzando in maniera logica le sue competenze e funzioni.

La predisposizione di un titolario è necessaria per smistare i documenti ai vari che compongono un ente e per ricomporla, a fine anno, quando vengono recuperate le pratiche chiuse e trasferite nell'archivio di deposito. Il titolario è necessario per l'archiviazione in Italia per tutti gli enti dotati di registro di protocollo (gli enti pubblici), fin dalla circolare del 1º marzo 1897, n. 17100/2. ([Wikipedia](https://it.wikipedia.org/wiki/Titolario_di_classificazione)).

Le Università italiane, come titolario di classificazione, di norma utilizzano "Titulus", giunto all' [edizione n.8 ](http://www.procedamus.it/images/materiali/Titolario_2013.pdf) e approvato dal Ministero con questo [provvedimento](http://www.procedamus.it/images/materiali/Titolario_Approvazione_DGA_2013.pdf).

La mia proposta è di definire il vocabolario controllato del titolario di classificazione degli archivi delle Università basandolo sul titolario "Titulus", considerato che molti software documentali negli Atenei (se non tutti) fanno riferimento a questo standard di classificazione.

Prima di inviare eventuali PR volevo chiedere se aveva senso iniziare a lavorarci.

**Comment by giorgialodi** [comment]
Ciao @gpirrotta, 
grazie per aver aperto questo interessante issue. Guardavo il titolario. Molto molto interessante. Per capire meglio: volevi creare un unico vocabolario controllato di due livelli con il primo livello che sono i titoli e poi un secondo livello con le varie voci oppure volevi agire diversamente?
Per esempio: vedo titolo II e vedo dei ruoli, alcuni dei quali veramente generali e applicabili anche in altri contesti (e.g., Presidente, Direttore Generale, Collegio Revisore dei Conti, ecc.). Sarebbe interessante capire se si riesce a creare un qualcosa di riutilizzabile anche in altri contesti; per esempio, un vocabolario specifico dei ruoli servirebbe come il pane! In questo caso l'ipotesi anche di scompattare il titolario a seconda dei vari titoli potrebbe valer la pena considerarla.
Inoltre, guardando alcuni termini mi sento di scrivere un consiglio: sarebbe utile guardare i vocabolari controllati attualmente disponibili per le organizzazioni perché vedo termini già definiti in altri vocabolari e quindi sarebbe utile pensare ai link  tra i vari vocabolari. 
Infine, questa cosa me la devo chiarire bene, ma vedo delle attività e dei servizi offerti (ho visto giusto?) e questo sarebbe ideale per l'ontologia dei servizi pubblici (servizi pubblici per le università). L'ontologia è la CPSV-AP_IT e potrebbe rientrare tra i vari modelli di servizi, in questo caso modelli di servizi per le università.
In sostanza per me questa cosa che proponi è molto importante e interessante. Da capire quanto è vocabolario controllato o quanto ontologia o quanto è ontologia da unire al vocabolario controllato :)

Giusto alcune note su come creiamo i vocabolari di OntoPiA (mi accorgo che non è stato scritto da nessuna parte). Per fare vocabolari controllati noi ci siamo dati questa metodologia:
1) i vocabolari controllati sono tutti dataset open data:
    - formato aperto
    - licenza aperta
    - metadatati secondo le specifiche dcat-ap_it
2) vengono forniti in più formati con almeno uno di tipo aperto. Tipicamente vengono pubblicati in excel, CSV, RDF/XML, RDF/Turtle e JSON-LD.
3) sono modellati principalmente mediante l'uso di SKOS e l'uso di XKOS (quest'ultimo per definire i livelli, se esistenti, delle possibili tassonomie - se c'è solo un livello si indicherà che ha solo un 1 livello)
4) si dichiara di che tipo è il vocabolario controllato: per esempio una CodeList oppure una Taxonomy o altro tipo
5) se fosse possibile aggiungere anche delle descrizioni dei vari termini sarebbe meglio :)
6) uso di URI w3id.org in inglese; quindi w3id.org/italia/controlled-vocabulary/....
7) nel repository di github la struttura a directory ha senso anche rispetto alla deferenziazione degli URI. Quindi si potrebbe fare https://w3id.org/italia/controlled-vocabulary/classifications-for-universities/titulus97 come URI del vocabolario (è un esempio)

**Comment by gpirrotta** [comment]
>Per capire meglio: volevi creare un unico vocabolario controllato di due livelli con il primo livello che sono i titoli e poi un secondo livello con le varie voci oppure volevi agire diversamente?

La mia idea era di creare un vocabolario controllato su due livelli.

> Per esempio: vedo titolo II e vedo dei ruoli, alcuni dei quali veramente generali e applicabili anche in altri contesti (e.g., Presidente, Direttore Generale, Collegio Revisore dei Conti, ecc.). Sarebbe interessante capire se si riesce a creare un qualcosa di riutilizzabile anche in altri contesti; per esempio, un vocabolario specifico dei ruoli servirebbe come il pane! In questo caso l'ipotesi anche di scompattare il titolario a seconda dei vari titoli potrebbe valer la pena considerarla.

Se vuoi creare un vocabolario dei ruoli allora potresti prendere quelli definiti dal titolo II di Titulus97 per le Università e unirli ad esempio a quelli del [titolario dei comuni](https://www.agid.gov.it/sites/default/files/repository_files/documenti_indirizzo/titolario_per_i_comuni.pdf) titolo II (pag.17)

> Inoltre, guardando alcuni termini mi sento di scrivere un consiglio: sarebbe utile guardare i vocabolari controllati attualmente disponibili per le organizzazioni perché vedo termini già definiti in altri vocabolari e quindi sarebbe utile pensare ai link tra i vari vocabolari.

Ok

> Infine, questa cosa me la devo chiarire bene, ma vedo delle attività e dei servizi offerti (ho visto giusto?) e questo sarebbe ideale per l'ontologia dei servizi pubblici (servizi pubblici per le università). L'ontologia è la CPSV-AP_IT e potrebbe rientrare tra i vari modelli di servizi, in questo caso modelli di servizi per le università.
> In sostanza per me questa cosa che proponi è molto importante e interessante. Da capire quanto è vocabolario controllato o quanto ontologia o quanto è ontologia da unire al vocabolario controllato :)

Non sono un archivista per cui non conosco benissimo il mondo degli archivi. Quello che so è che il piano di classificazione rappresenta l'ossatura di tutti i documenti che arrivano, partono e vengono scambiati all'interno di tutti gli enti della pubblica amministrazione. Tutti i documenti di una pubblica amministrazione per essere protocollati devono essere obbligatoriamente classificati.
La classificazione io la vedo più legata al mondo dell'archivistica che al mondo dei servizi offerti. All'Università abbiamo due strumenti che possono essere utilizzati per il mondo dei servizi:

1. la tabella Procedamus dei [procedimenti amministrativi](http://www.procedamus.it/images/tabella/ProcedamusTabella30apr2017.xls), definita dal gruppo di lavoro inter-istituzionale [PROCEDAMUS](http://www.procedamus.it), che raccoglie diverse centinaia di voci tra procedimenti amministrativi,attività e affari del mondo universitario; magari potrebbe diventare un vocabolario controllato?
2. la carta dei Servizi di Ateneo; una prova che voglio fare è applicare l'ontologia CPSV-AP_IT alla carta dei servizi dell'Università di Messina e analizzare la flessibilità dell'ontologia. Non l'ho ancora vista bene però devo capire se e in che modo riuscire a rappresentare gli indicatori e i valori programmati di qualità per ciascun servizio che noi qui usiamo per il monitoraggio e per eventuali reclami da parte degli stakeholder.

> 7. nel repository di github la struttura a directory ha senso anche rispetto alla deferenziazione degli URI. Quindi si potrebbe fare https://w3id.org/italia/controlled-vocabulary/classifications-for-universities/titulus97 come URI del vocabolario (è un esempio)

Essendo il titolario di classificazione presente in tutte le pubbliche amministrazioni e riferendosi principalmente agli archivi delle PA avevo immaginato la seguente struttura.

/classifications-for-archives/universities 
/classifications-for-archives/schools 

Ho preso come esempio i titolari di università e scuole perchè entrambi sono stati approvati dal Ministero quindi potrebbero essere rappresentati come vocabolari controllati.

Cosa ne pensi? Per i titolari ritieni sia la strada migliore? Avevo iniziato a lavorarci però attendo tuoi consigli.

**Comment by giorgialodi** [comment]
> La mia idea era di creare un vocabolario controllato su due livelli.

va bene.
 
> Se vuoi creare un vocabolario dei ruoli allora potresti prendere quelli definiti dal titolo II di Titulus97 per le Università e unirli ad esempio a quelli del [titolario dei comuni](https://www.agid.gov.it/sites/default/files/repository_files/documenti_indirizzo/titolario_per_i_comuni.pdf) titolo II (pag.17)

Molto interessante. Secondo me potremmo fare un vocabolario controllato dei ruoli, il publication office europeo per esempio ce l'ha ed è calato sui suoi ruoli. Sarebbe da capire  se la classificazione delle professioni già copre tutto. In questo posso sentire ISTAT. Se sei interessato a collaborare proviamo a sentirci anche su questo :)

> Non sono un archivista per cui non conosco benissimo il mondo degli archivi. Quello che so è che il piano di classificazione rappresenta l'ossatura di tutti i documenti che arrivano, partono e vengono scambiati all'interno di tutti gli enti della pubblica amministrazione. Tutti i documenti di una pubblica amministrazione per essere protocollati devono essere obbligatoriamente classificati.
> La classificazione io la vedo più legata al mondo dell'archivistica che al mondo dei servizi offerti. All'Università abbiamo due strumenti che possono essere utilizzati per il mondo dei servizi:
> 
>     1. la tabella Procedamus dei [procedimenti amministrativi](http://www.procedamus.it/images/tabella/ProcedamusTabella30apr2017.xls), definita dal gruppo di lavoro inter-istituzionale [PROCEDAMUS](http://www.procedamus.it), che raccoglie diverse centinaia di voci tra procedimenti amministrativi,attività e affari del mondo universitario; magari potrebbe diventare un vocabolario controllato?

Sono un po' scettica sulla forma vocabolario controllato per questi tipi di dati sai. Ho come l'impressione che non si riesca a coprire sempre veramente tutto. Questa tabella comunque è utilissima per il lavoro sul catalogo dei servizi nazionale. Grazie mille per il riferimento.

> 
>     2. la carta dei Servizi di Ateneo; una prova che voglio fare è applicare l'ontologia CPSV-AP_IT alla carta dei servizi dell'Università di Messina e analizzare la flessibilità dell'ontologia. Non l'ho ancora vista bene però devo capire se e in che modo riuscire a rappresentare gli indicatori e i valori programmati di qualità per ciascun servizio che noi qui usiamo per il monitoraggio e per eventuali reclami da parte degli stakeholder.

Questa cosa sarebbe fantastica! Non mi è chiaro il passaggio sugli indicatori e i valori programmati, ma se riuscissimo a mappare i servizi dell'università di Messina con l'ontologia sarebbe un ottimo lavoro (magari poi la città di messina può pubblicare il dataset come open data!). E ci vedo anche un lavoro più ampio: potremmo infatti creare modelli di servizi per altre università nella piattaforma nazionale dei servizi (catalogo servizi, servizi.gov.it) e potremmo così iniziare a documentarli :)
Fammi sapere se riesci a fare progressi sull'applicazione di CPSV-AP_IT. La mia porta è sempre aperta per qualsiasi dubbio. Anzi, pensavo: perché non vi unite come Università di Messina al progetto servizi.gov.it? L'università è categoria di PA attualmente assente tra i vari early adopter.

> Essendo il titolario di classificazione presente in tutte le pubbliche amministrazioni e riferendosi principalmente agli archivi delle PA avevo immaginato la seguente struttura.

> /classifications-for-archives/universities
> /classifications-for-archives/schools
> 
> Ho preso come esempio i titolari di università e scuole perchè entrambi sono stati approvati dal Ministero quindi potrebbero essere rappresentati come vocabolari controllati.
> 
> Cosa ne pensi? Per i titolari ritieni sia la strada migliore? Avevo iniziato a lavorarci però attendo tuoi consigli.

Ma secondo te potrebbe essere anche una cosa tipo classifications-for-documents/universities-titulus e classifications-for-documents/shools-titulus? Prima dicevi che tutti i documenti sono classificati prima di essere protocollati e mi sembra che questi titolari di classificazione servano a questo scopo, giusto?
Comunque la strada ormai è delineata, non rimane che mettersi all'opera :) 
Bisogna capire chi è poi l'amministrazione titolare di questi titolari, ma immagino tu conosca l'intera governance dalla cosa.

Grazie mille Giovanni!

**Comment by gpirrotta** [comment]
> va bene.

Ottimo, appena la completo ti invio una PR
 
> Molto interessante. Secondo me potremmo fare un vocabolario controllato dei ruoli, il publication office europeo per esempio ce l'ha ed è calato sui suoi ruoli. Sarebbe da capire se la classificazione delle professioni già copre tutto. In questo posso sentire ISTAT. Se sei interessato a collaborare proviamo a sentirci anche su questo :)

Si, mi interesserebbe molto.

> Sono un po' scettica sulla forma vocabolario controllato per questi tipi di dati sai. Ho come l'impressione che non si riesca a coprire sempre veramente tutto. Questa tabella comunque è utilissima per il lavoro sul catalogo dei servizi nazionale. Grazie mille per il riferimento.

In effetti la tabella dei procedimenti amministrativi è molto discrezionale. Noi stessi all'Università di Messina siamo partiti da quella come standard di riferimento ma in sede di mappatura ne abbiamo aggiunti altri.


> > 2. la carta dei Servizi di Ateneo; 
> 
> Questa cosa sarebbe fantastica! Non mi è chiaro il passaggio sugli indicatori e i valori programmati, ma se riuscissimo a mappare i servizi dell'università di Messina con l'ontologia sarebbe un ottimo lavoro (magari poi la città di messina può pubblicare il dataset come open data!). E ci vedo anche un lavoro più ampio: potremmo infatti creare modelli di servizi per altre università nella piattaforma nazionale dei servizi (catalogo servizi, servizi.gov.it) e potremmo così iniziare a documentarli :)

Esatto, vorrei **ontopizzare**  la carta dei servizi dell'Università e vedere cosa ne esce fuori ;-)
Non so però quanto CPSV-AP_IT riesca a modellare il concetto di Qualità del Servizio (QoS).
La carta dei servizi dell'Università di Messina è stata progettata nativamente con dimensioni (e sottodimensioni), indicatori, formule e valori programmati per ciascun servizio. A partire da queste metriche riusciamo a monitorare la qualità di tutti i servizi. 
Tutti questi concetti (mi sembra) non sono presenti in CPSV-AP_IT e sarebbe interessante riuscire a estenderla in modo da poter modellare anche questo aspetto fondamentale dei servizi.
Inoltre le dimensioni sono fornite dalla normativa per cui potrebbero diventare un vocabolario controllato. Come riferimento ti lascio il link alla [carta dei servizi dell'Università](https://www.unime.it/sites/default/files/Carta_Servizi_UNIME_2018_rev_2.pdf).

> Fammi sapere se riesci a fare progressi sull'applicazione di CPSV-AP_IT. La mia porta è sempre aperta per qualsiasi dubbio. Anzi, pensavo: perché non vi unite come Università di Messina al progetto servizi.gov.it? L'università è categoria di PA attualmente assente tra i vari early adopter.

Mi piacerebbe molto, cosa bisogna fare? Io intanto ne parlo con la governance.

 > Ma secondo te potrebbe essere anche una cosa tipo classifications-for-documents/universities-titulus e classifications-for-documents/shools-titulus? Prima dicevi che tutti i documenti sono classificati prima di essere protocollati e mi sembra che questi titolari di classificazione servano a questo scopo, giusto?

Ok per classifications-for-documents/universities-titulus

> Grazie mille Giovanni!

Grazie a te!

**Comment by giorgialodi** [comment]
> Ottimo, appena la completo ti invio una PR

Perfetto!

> > Molto interessante. Secondo me potremmo fare un vocabolario controllato dei ruoli, il publication office europeo per esempio ce l'ha ed è calato sui suoi ruoli. Sarebbe da capire se la classificazione delle professioni già copre tutto. In questo posso sentire ISTAT. Se sei interessato a collaborare proviamo a sentirci anche su questo :)
> 
> Si, mi interesserebbe molto.

Ok, allora mettiamolo tra i TODO :) 

> > Sono un po' scettica sulla forma vocabolario controllato per questi tipi di dati sai. Ho come l'impressione che non si riesca a coprire sempre veramente tutto. Questa tabella comunque è utilissima per il lavoro sul catalogo dei servizi nazionale. Grazie mille per il riferimento.
> 
> In effetti la tabella dei procedimenti amministrativi è molto discrezionale. Noi stessi all'Università di Messina siamo partiti da quella come standard di riferimento ma in sede di mappatura ne abbiamo aggiunti altri.

Ecco perché sono scettica sul vocabolario controllato mentre sono più favorevole a creare il dataset che segue l'ontologia dei servizi pubblici.

> > > 1. la carta dei Servizi di Ateneo;
> > 
> > 
> > Questa cosa sarebbe fantastica! Non mi è chiaro il passaggio sugli indicatori e i valori programmati, ma se riuscissimo a mappare i servizi dell'università di Messina con l'ontologia sarebbe un ottimo lavoro (magari poi la città di messina può pubblicare il dataset come open data!). E ci vedo anche un lavoro più ampio: potremmo infatti creare modelli di servizi per altre università nella piattaforma nazionale dei servizi (catalogo servizi, servizi.gov.it) e potremmo così iniziare a documentarli :)
> 
> Esatto, vorrei **ontopizzare** la carta dei servizi dell'Università e vedere cosa ne esce fuori ;-)
> Non so però quanto CPSV-AP_IT riesca a modellare il concetto di Qualità del Servizio (QoS).
> La carta dei servizi dell'Università di Messina è stata progettata nativamente con dimensioni (e sottodimensioni), indicatori, formule e valori programmati per ciascun servizio. A partire da queste metriche riusciamo a monitorare la qualità di tutti i servizi.
> Tutti questi concetti (mi sembra) non sono presenti in CPSV-AP_IT e sarebbe interessante riuscire a estenderla in modo da poter modellare anche questo aspetto fondamentale dei servizi.
> Inoltre le dimensioni sono fornite dalla normativa per cui potrebbero diventare un vocabolario controllato. Come riferimento ti lascio il link alla [carta dei servizi dell'Università](https://www.unime.it/sites/default/files/Carta_Servizi_UNIME_2018_rev_2.pdf).

No, non c'è il concetto di QoS per i servizi in CPSV-AP_IT. CPSV-AP_IT serve per documentare tutti i servizi e tutte quelle caratteristiche che servono al pubblico per usufruire del servizio.
Sono d'accordo con te sull'estensione: si potrebbe fare un'ontologia a parte su questo (e sarebbe molto utile avere un modo uniforme su scala nazionale di modellare indicatori di monitoraggio) che poi si collega con CPSV-AP_IT. Conosco questo vocabolario https://www.w3.org/TR/vocab-dqv/ che è collegato ai dataset e alle distribuzioni (per intenderci al DCAT) ma potrebbe essere interessante capire se il modello è replicabile per applicarlo ad altri contesti (come i servizi).
Su questo mi segno che potrebbe essere oggetto di approfondimento :)

> > Fammi sapere se riesci a fare progressi sull'applicazione di CPSV-AP_IT. La mia porta è sempre aperta per qualsiasi dubbio. Anzi, pensavo: perché non vi unite come Università di Messina al progetto servizi.gov.it? L'università è categoria di PA attualmente assente tra i vari early adopter.
> 
> Mi piacerebbe molto, cosa bisogna fare? Io intanto ne parlo con la governance.

Ne parlo internamente al gruppo di servizi.gov.it. Poi ti faccio sapere :) 

> > Ma secondo te potrebbe essere anche una cosa tipo classifications-for-documents/universities-titulus e classifications-for-documents/shools-titulus? Prima dicevi che tutti i documenti sono classificati prima di essere protocollati e mi sembra che questi titolari di classificazione servano a questo scopo, giusto?
> 
> Ok per classifications-for-documents/universities-titulus

Ottimo!!! Aggiudicato! :-)

**Comment by giorgialodi** [comment]
@gpirrotta direi che questa issue la possiamo chiudere visto che ora il titulus è parte integrante di OntoPiA :) Se per caso mi sono dimenticata qualcosa riapri pure l'issue!
