### ISSUE TITLE
Proposta creazione vocabolari controllati per l'ambito universitario

### ISSUE THREAD

**Issue by gpirrotta** [italia/daf-ontologie-vocabolari-controllati#50]
Per garantire il corretto funzionamento delle Università italiane e per caratterizzare aspetti peculiari di questo dominio, la normativa italiana definisce il seguente insieme di classificazioni:

* Ambiti disciplinari
* Aree Disciplinari
* Attività formative
* Settori scientifico-disciplinari
* Tipologia dei titoli di studio
* Macrosettori
* Settori concorsuali
* Classi di Lauree
* Tipologie di docenti
* Tipologie di studenti

Se da un lato l'obiettivo dei vocabolari controllati di ontopia è quello di essere i più trasversali possibili, in modo da poter essere riutilizzati dal maggior numero di PA, anche tra loro eterogenee
(penso ad esempio al riutilizzo del vocabolario di voci territoriali - città, province, etc.), dall'altro potrebbe essere anche utile definire vocabolari controllati ad-hoc per specifiche tipologie di PA.

Prendendo per esempio in considerazione il mondo delle università, penso ad una cosa del tipo:

`https://w3id.org/italia/controlled-vocabulary/classifications-for-universities/scientific-disciplinary-sector`

`https://w3id.org/italia/controlled-vocabulary/classifications-for-universities/academic-recuitment-field
`

`https://w3id.org/italia/controlled-vocabulary/classifications-for-universities/degree-classes
`
`etc...
`

Gli elementi delle classificazioni sopra menzionate costituiscono la base su cui vengono sviluppate le applicazioni utilizzate in ciascuna università.
Utilizzare vocabolari unici per il dominio universitario potrebbe aiutare molto gli atenei a utilizzare un linguaggio comune per ottenere la tanto agognata interoperabilità semantica, non solo tra le diverse PA ma anche e soprattutto tra le applicazioni sviluppate internamente e in uso nella stessa PA.

Se l'idea è condivisa posso mandare delle PR, modificando anche  #48 correggendo la URI nel seguente modo:
`https://w3id.org/italia/controlled-vocabulary/classifications-for-universities/documents-titulus
`

@giorgialodi cosa ne pensi, ti convince? Ha senso secondo te ragionare ad-PA?

**Comment by giorgialodi** [comment]
Ciao @gpirrotta secondo me più che ragionare per singola PA direi che si ragione per singole tipologie di dati che sono specifici per certi tipi di PA. Mia personale esperienza che vorrei condividere, e chiedere a te che ne pensi, è questa: non esiste LA classificazione che vale per tutto, ma tipicamente a seconda anche del punto di vista della classificazione, una classificazione può cogliere alcuni elementi e altri no. Provare quindi a creare vocabolari che vadano bene per qualsiasi tipo di dato secondo me non è la strada da percorrere per avere un risultato efficace. Di solito si fanno le varie classificazioni e poi si mappa e, grazie anche ai linked data, queste mappature sono di più facile lettura anche da parte di dispositivi digitali. Pertanto la tua proposta mi sembra sensata. Nel merito, rispetto  all'elenco dei possibili vocabolari controllati che facevi, avrei un'osservazione e una domanda:
1) **domanda**: quelle classificazioni sono ufficiali per le università? Se sì che riferimenti, anche normativi esistono?
2) **osservazione** vedo ambiti disciplinari e titoli di studio. Su questi due aspetti abbiamo già fatto due vocabolari controllati, il primo si raccorda proprio con quanto fatto dal MIUR, il secondo è classificazione ufficiale di ISTAT. Magari per questi due ambiti possiamo, più che creare vocabolari controllati ex-novo, creare dei mapping (come il caso del mapping dei temi DCAT-AP_IT con quelli di Eurovoc) verso i due già esistenti. Che ne pensi?

Per gli altri invece direi di procedere. Mi piace "classifications-for-universities", anche per il titolario.

Comunque mi piacerebbe conoscere l'opinione anche di @seralf e di @marco-brandizi che hanno diverse esperienze e competenze in merito.

**Comment by marco-brandizi** [comment]
Ciao @gpirrotta, @giorgialodi.

In realtà non sono così esperto dello specifico dominio, che, mi pare, sta a cavallo tra la gestione della formazione e la catalogazione delle produzione accademica.

Mi sembra buono cercare di mettere a punto dei vocabolari riutilizzabili il più possibile e non troppo specifici di un istituto, una disciplina, o la nazione. A questo proposito, siccome è inevitabile avere piccole differenze tra contesti diversi, mi sembra importante che i progetti specifici riusino e facciano mapping il più possibile.

Inoltre, mi pare rilevante la distinzione tra vocaboli relativi alla gestione (es, tipo di università, tipo di studente o ruolo del personale) e quelli relativi agli argomenti. Questi ultimi sono molto più vari e più difficili da confinare in vocabolari, esistono progetti del genere ([es 1](https://github.com/FAIRsharing/subject-ontology), [es 2](https://www.bbc.co.uk/ontologies/curriculum)), ma credo sia interessante integrare il lavoro manuale con la [classificazione automatica](https://technologies.kmi.open.ac.uk/rexplore/).

**Comment by marco-brandizi** [comment]
Beh, se ci sono classificazioni nella normativa, vanno "ontologizzate" quelle. Ma conviene comunque mappare/estendere da vocabolari esistenti. Bisogna poi vedere cosa conviene usare nella pratica: magari gli operatori sono già abituati alle classificazioni definite dalla norma, e allora le applicazioni dovrebbero presentare quelle, allineate ad altro. Oppure fann più uso di altre tassonomie, e allora convience che si mappino quelle sulla normativa esistente.

**Comment by gpirrotta** [comment]
> Beh, se ci sono classificazioni nella normativa, vanno "ontologizzate" quelle. Ma conviene comunque mappare/estendere da vocabolari esistenti. Bisogna poi vedere cosa conviene usare nella pratica: magari gli operatori sono già abituati alle classificazioni definite dalla norma, e allora le applicazioni dovrebbero presentare quelle, allineate ad altro. Oppure fann più uso di altre tassonomie, e allora convience che si mappino quelle sulla normativa esistente.

Solitamente le applicazioni universitarie vanno di pari passo con la normativa per cui l'idea è di creare vocabolari ad-hoc cercando, al tempo stesso, di creare più relazioni possibili con altre ontologie europee.

**Comment by gpirrotta** [comment]
> > @gpirrotta sulla PR per il titolario aspetto quindi il cambio come suggerisci ok?
> 
> Ok

Ho aggiornato la PR #48

**Comment by giorgialodi** [comment]
@gpirrotta @marco-brandizi grazie mille a entrambi per lo scambio.
Volendo fare un riassunto di quanto discusso direi allora che potremmo procedere così:
1) creiamo questi vocabolari e li mettiamo sotto classifications-for-universities, anche per quelli che sembrano già esserci ma che in realtà sono più specifici per le università (suggerisco però di dare nomi differenti in generale, sebbene gli URI saranno per ovvi motivi diversi)
2) creiamo mapping (li allineiamo). Faccio un esempio:  nel caso di subject-disciplines, se ci sono voci del vocabolario esistente che sono proprio lo stesso concetto rispetto al vocabolario ambiti disciplinari qui menzionato più specifico possiamo aggiungere assiomi di allineamento con skos tipo exact match oppure related match a seconda dei casi. Così abbiamo il linking tra i vocabolari e potremmo poi abilitare tali collegamenti anche in sede di navigazione dei vocabolari stessi nel relativo catalogo (cc @seralf). 
Che ne pensate tutti? 
@gpirrotta controllo tutte le PR :)

**Comment by seralf** [comment]
ciao @Giorgia e tutti
grazie per tenermi nel loop: non ho ancora avuto modo di leggere il thread
ma volentieri mi leggo (e studio!) le varie cose proposte, grazie!

PS: bello inizino ad esserci anche contributi "esterni" IMHO

Il giorno lun 17 dic 2018 alle ore 14:48 giorgialodi <
notifications@github.com> ha scritto:

**Comment by seralf** [comment]
> Poiché il settore scientifico-disciplinare è l'ultima foglia di un insieme di classificazioni/tassonomie su cui ruota tutto il funzionamento universitario, vedrei meglio un vocabolario controllato ad-hoc, con una rappresentazione ad esempio di questi [livelli](https://it.wikipedia.org/wiki/Settore_scientifico-disciplinare), a cui associare anche il livello delle afferenze, non riportato nella pagina di wikipedia.
> Un altro problema che ho rilevato è anche che, quando parlo di **ambiti disciplinari**, non mi riferisco a quelli presenti nel vocabolario **subject-disciplines**, ma [...]

Rileggendovi mi sembra emergere quanto l'attuale `subject-disciplines` sia forse più specifico di quanto avessi messo a fuoco finora, molto cioè orientato all'ambito artistico/culturale, e mi sembra perciò potenzialmente interessante ed utile l'aggiunta di altri vocabolari su ambiti differenti, da mappare all'occorrenza tra loro.

 
> Per quanto riguarda invece i **titoli di studio** voglio rifletterci sopra un pò. [...]

Mi sembrano molto interessanti le riflessioni, anche guardando il problema da un punto di vista extra-universitario: ad esempio nel caso si vogliano descrivere curriculum personali (vedi varie esperienze di modellazione CV/resume, tra cui quella proposta da @marco-brandizi  sopra), ai fini di pubblicazione per la trasparenza, o per il mercato del lavoro etc.

**Comment by gpirrotta** [comment]
Ciao @giorgialodi e tutti, 
scusate la lunga assenza.

Io allora procederei iniziando dalla tassonomia dei settori scientifico disciplinari secondo il [D.M. 855 del 13/10/2015](http://attiministeriali.miur.it/anno-2015/ottobre/dm-30102015.aspx) che definisce le seguenti classificazioni:


1. **Macrosettori concorsuali (MSC)**
2. **Settori Concorsuali (SC)**
3. **Settori Scientifico disciplinari (SSD)**

A sua volta i **Macrosettori** sono suddivise per **Aree** definite dal Consorzio Universitario Nazionale (**CUN**), per cui avremmo una tassonomia a 4 livelli.

1) **Aree (CUN)**
2) **Macrosettori**
3) **Settori Concorsuali**
4) **Settori Scientifico disciplinari**

Su [Wikipedia](https://it.wikipedia.org/wiki/Settore_scientifico-disciplinare) potete vedere il quadro completo.

Per quanto riguarda il nome delle URI, nel succitato D.M., all'[allegato D](http://attiministeriali.miur.it/media/265763/allegato_d.pdf) sono presenti le seguenti traduzioni:

**Settore scientifico disciplinare** = academic discipline
**Settore concorsuale** = academic recruitment field
**Macrosettore concorsuale** = group of academic recruitment fields

Il settore scientifico disciplinare l'ho visto tradotto veramente anche in altri modi: scientific disciplinary sector, disciplinary-scientific sector, etc.

Di seguito due proposte per il naming delle URI.

**Esempio**
Area = 01
Macrosettore Concorsuale = 01/A
Settore Concorsuale = 01/A1
Settore scientifico-disciplinare = MAT/01

**Proposta 1**:
**URI per Area**:                                
classifications-for-universities/academic-discipline/Area-01
**URI per Macrosettore Concorsuale**:            
classifications-for-universities/academic-discipline/MSC-01-A
**URI per Settore Concorsuale**:                 
classifications-for-universities/academic-discipline/SC-01-A1
**URI per Settore Scientifico Disciplinare**:    
classifications-for-universities/academic-discipline/SSD-MAT-O1

**Proposta 2**:
**URI per Area:**                                
classifications-for-universities/academic-discipline-area/01
**URI per Macrosettore Concorsuale:**            
classifications-for-universities/academic-recruitment-field-group/01-A
**URI per Settore Concorsuale:**                
classifications-for-universities/academic-recruitment-field/01-A1
**URI per Settore Scientifico Disciplinare:**    
classifications-for-universities/academic-discipline/MAT-O1

Prima di generare il vocabolario e la PR potreste darmi un feedback a riguardo?
Grazie

**Comment by marco-brandizi** [comment]
@gpirrotta a naso la 1), per almeno un paio di motivi:

  - probabilmente è più facile passare da 'accession' come msc-01-a a URI e viceversa (con la due dovresti avere qualcosa per tradurre msc in/da /academic-recruitment-field-group)

- avere troppi prefissi URI diversi è scomodo in diversi contesti. Per esempio, non mi ricordo se in Jena o SPARQL, non puoi scrivere `univoc:academic-recruitment-field-group/01-A` (ie, combinare prefissi namespace e code URI che contengono '/'), sei costretto prima a definire un prefisso a parte e poi usare quello, eg, `univoc-msc:01-A`.

**Comment by gpirrotta** [comment]
> @gpirrotta a naso la 1), per almeno un paio di motivi:

@marco-brandizi in effetti anch'io sono più propenso per la 1).

La 2) l'ho inserita per una questione di coerenza tra naming e vocaboli ma sin dall'inizio non mi convinceva molto.

**Comment by giorgialodi** [comment]
Ciao a tutti,
eccomi! Intanto a tutta birra con le proposte di @gpirrotta che ringrazio per questi suoi contributi preziosissimi :)
Per quanto riguarda gli URI, per una questione di uniformità direi classifications-for-universities/academic-discipline--> classifications-for-universities/academic-disciplines
Invece tra le due proposte (1 e 2) direi assolutamente la 1.  Grazie anche a @marco-brandizi per i suoi contributi che ci aiutano a migliorare e a prendere le strade giuste in base anche al riuso.
Buona giornata a tutti

**Comment by gpirrotta** [comment]
Qui la PR #52

**Comment by giorgialodi** [comment]
ciao a tutti, ho fatto merge. Il vocabolario è ufficialmente in OntoPiA :-) Grazie mille per il contributo/supporto! 
Mi sono però persa: rispetto all'issue iniziale, abbiamo coperto un pezzo della normativa per le classificazioni vero? /cc @gpirrotta  Se sì tengo ancora aperto l'issue

**Comment by gpirrotta** [comment]
La  #52 copre le seguenti classificazioni:
1) Aree (CUN)
2) Macrosettori
3) Settori Concorsuali
4) Settori Scientifico disciplinari

Sì, è meglio se rimane aperta perchè ne mancano alcune anche se il grosso è stato già _merged_.

**Comment by gpirrotta** [comment]
Ciao tutti,
volendo adesso allineare le _academic-disciplines_ delle università con le [_subject-disciplines_ ](https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-culture/subject-disciplines) e
premesso che per ora intendo allineare solo i concetti che hanno la stessa identica **label** vi chiedo le seguenti cose:

* conosco il dominio universitario per cui so cos'è un settore scientifico disciplinare ma non conosco altrettanto bene gli ambiti disciplinari del vocabolario controllato [_subject-disciplines_ ](https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-culture/subject-disciplines) per cui vi chiedo, **quanto** i due concetti sono uguali secondo voi? **owl:sameAs** e **skos:exactMatch**? (mi sembrano troppo forti), **skos:relatedMatch**?, **skos:closeMatch**? Qualcos'altro?

`<https://w3id.org/italia/controlled-vocabulary/classifications-for-universities/academic-disciplines/Area-02> skos:{what?} <https://w3id.org/italia/controlled-vocabulary/classifications-for-culture/subject-disciplines/003>`

* come li chiamo i file di allineamento?
_academic-disciplines-alignments.ttl
academic-disciplines-alignments.rdf
academic-disciplines-alignments.jsonld_

Consigli?

**Comment by giorgialodi** [comment]
Ciao @gpirrotta, il vocabolario controllato delle subject disciplines era più orientato al mondo dei beni culturali (è infatti utilizzato lì per controllare gli individui della classe categoria prevalente di Cultral-On) anche se c'era un raccordo con alcune discipline così come definite dal MIUR. 
Io procederei così:
1) vedrei la documentazione del vocabolario subject discipline (nel readme c'è una descrizione della metodologia seguita per crearlo) e se ci sono delle definizioni per ogni voce cercherei di capirle meglio.
2) a meno che non sia proprio lampante che è la stessa cosa, per cui userei skos:exactMatch, andrei più per un linking più debole con le proprietà che anche tu hai indicato (e.g., relatedMatch o closeMatch, in quest'ultimo caso quando forse le due cose sono di fatto molto vicine).

Per i vocabolari controllati non abbiamo fatto file di allineamento a parte (fatti invece per le ontologie) ma dentro le voci del vocabolario stesso abbiamo messo gli assiomi di allineamento.  Così quando uno naviga ciascuna voce del vocabolario sa anche se quella voce corrisponde a un'altra di un altro vocabolario esistente allo stato dell'arte. Farei la stessa cosa qui. Magari inserirei nel vocabolario degli ambiti per le università i relativi linking a quello di subject disciplines (e volendo anche viceversa).
Che ne dici?

**Comment by gpirrotta** [comment]
Io mi sono fatto l'idea che gli ambiti disciplinari per i beni culturali e i settori scientifico-disciplinari non sono esattamente la stessa cosa per cui in fase di allineamento non vedrei bene né _owl:sameAs_ né _skos:exactMatch_. 
Per esigenze del vocabolario, infatti, a volte vengono presi i concetti MIUR e suddivisi in più concetti per i beni culturali.
Ad. es.
`scienze matematiche e informatiche (D.M. 4 ottobre 2000 – Area 01) diviso in: scienze matematiche; scienze informatiche`

In questo primo allineamento, ad esatta corrispondenza di **label**, io sarei per l'utilizzo di _skos:relatedMatch_ che mi dà l'idea di un collegamento sufficientemente congruo, cioè voglio poter dire che due concetti sono tra di loro collegati perchè trattano lo stesso **topic** ma non sono proprio la stessa cosa: uno è un ambito disciplinare per i beni culturali e l'altro è un settore scientifico-disciplinare utilizzato nel mondo universitario, con propria normativa, regole, etc.

A mo' di esempio assomiglia molto al collegamento del concetto  _pomodoro_ in un ipotetico vocabolario di botanica (dove il pomodoro è considerato un frutto) con il concetto _pomodoro_ in un altro ipotetico vocabolario culinario (dove il pomodoro è considerato una verdura). È sempre un pomodoro ma in contesti diversi assume significati diversi. 

Ripeto, non conosco bene _subject-disciplines_ per cui potrei sbagliarmi, però io procederei in questo modo.

> Per i vocabolari controllati non abbiamo fatto file di allineamento a parte (fatti invece per le ontologie) ma dentro le voci del vocabolario stesso abbiamo messo gli assiomi di allineamento. Così quando uno naviga ciascuna voce del vocabolario sa anche se quella voce corrisponde a un'altra di un altro vocabolario esistente allo stato dell'arte. Farei la stessa cosa qui. Magari inserirei nel vocabolario degli ambiti per le università i relativi linking a quello di subject disciplines (e volendo anche viceversa).
> Che ne dici?

Ok, allora inserisco gli allineamenti nello stesso file del vocabolario. Un'ultima cosa. 
Quando dici **viceversa** intendi inserire le triple invertite _subject-disciplines_ _skos:qualcosa_ _academic-disciplines_ sempre nello stesso file del vocabolario _academic-disciplines.{format}_ oppure sposto quelle invertite nel file _subject-disciplines.{format}_?

**Comment by giorgialodi** [comment]
Ciao @gpirrotta , per me il tuo ragionamento sull'uso di relatedMatch fila molto e procederei come hai scritto. In effetti il vocabolario subject disciplines è stato creato apposta per l'ambito beni culturali, quindi ci sta. 
Per l'ultimo punto intendo che possono mettere assiomi di allineamento nel vocabolario academic-disciplines con qualcosa del tipo: academic-disciplines skos:relatedMatch subject-disciplines e nel vocabolario subject-disciplines mettere degli assiomi di allineamento verso academic-disciplines.
In ogni caso inizierei con il primo caso: dentro al vocabolario academic-disciplines metterei gli assiomi di allineamento a subject-disciplines. Poi vediamo se fare anche l'altro verso :)
Grazie come sempre Giovanni!

**Comment by giorgialodi** [comment]
@gpirrotta, tutti, giusto per informarti/vi che il frutto di questo lavoro di comunità è anche navigabile online ora. Se accedete via html agli URI dei due vocabolari creati li potete navigare. Per esempio: https://ontopia.daf.teamdigitale.it/lodview/controlled-vocabulary/classifications-for-universities/academic-disciplines.html

**Comment by gpirrotta** [comment]
Grazie @giorgialodi !!!

**Comment by giorgialodi** [comment]
Se per tutti va bene, direi che possiamo chiudere questo issue in quanto il frutto dell'interazione è evidente. Nel caso ci sia necessità di lavorare su altri suoi aspetti possiamo aprire issue a parte.
