### ISSUE TITLE
:auctionBaseAmount - Ontologia Contratti Pubblici

### ISSUE THREAD

**Issue by giorgiobevilacqua** [italia/daf-ontologie-vocabolari-controllati#57]
il dominio della property :auctionBaseAmount andrebbe cambiato da :procurementProject a :Lot

si tratta infatti dell'importo base d'asta per l'aggiudicazione dei singoli lotti

**Comment by giorgialodi** [comment]
Ciao @giorgiobevilacqua, grazie mille! Verifichiamo la cosa allora.

**Comment by giorgialodi** [comment]
@giorgiobevilacqua ah forse è stato fatto così per far in modo che l'importo potesse essere associato anche alla procurementprocedure? Dobbiamo rivderlo anche in base alla relazione che intercorre tra la procurementprocedure e il lot

**Comment by giorgialodi** [comment]
@giorgiobevilacqua dai dati emerge che auctionBaseAmount si applica sia a Procedure che a Lot e gli importi sono differenti: Procedura = somma degli importi dei lotti.
Avere pertanto auctionBaseAmount a livello di ProcurementProject aiuta. SI lascia pertanto invariato l'attuale domain della proprietà. 
Da ricordarsi di rifattorizzare comunque l'ontologia per via dell'ontologia che sta nascendo per rispondere all'issue https://github.com/italia/daf-ontologie-vocabolari-controllati/issues/59
