### ISSUE TITLE
Honorifics di una Persona

### ISSUE THREAD

**Issue by luigi-asprino** [italia/daf-ontologie-vocabolari-controllati#58]
Ciao,

Esiste in OntoPiA un modo per specificare quello che gli inglesi chiamano [honorific](https://en.wikipedia.org/wiki/English_honorifics) di una persona (eg. Mr, Mrs, Dr ecc.)?

Luigi

**Comment by anuzzolese** [comment]
No, ma potrebbe essere utile aggiungerlo.

**Comment by giorgialodi** [comment]
Ciao @luigi-asprino, @anuzzolese ti ha risposto perfettamente :) Possiamo aggiungerlo nell'ontologia delle Persone (CPV).

**Comment by giorgialodi** [comment]
@luigi-asprino @anuzzolese in FOAF c'è la proprietà title ma c'è questo commento: "This property is a candidate for deprecation in favour of 'honorificPrefix'". Direi è proprio quello che stai cercando  @luigi-asprino vero?

**Comment by luigi-asprino** [comment]
Si si, infatti per ora sto usando questa.
Però sarebbe meglio aggiungerla a CPV. 
I modi in cui l'ho vista chiamare questa proprietà sono honorificPrefix, suffix o title.

**Comment by luigi-asprino** [comment]
Cerco di iniziare a sistemare gli issue che sollevo :-)
Ho fatto un fork del repository dove ho modellato una soluzione per risolvere questa issue.
Ho aggiunto a CPV la classe: 
1) Title (che nella mia idea deve essere popolata con un vocabolario controllato di titoli/appellativi di una persona). Title ha un nome (il titolo, es. Avv.) e una lingua (permette di specificare vocabolari controllati rispetto a lingue diverse, es. it). Per modellare la lingua ho importato l'ontologia Language.
2) La proprietà CPV:hasTitle permette di collegare una persona ad un suo titolo.
Trovate l'ontologia modificata qui [1].

Ho pensato all'uso di un vocabolario controllato invece che una datatype property, per evitare che il valore della datatype fosse forzato (e.g. più titoli e/o  formati diversi nel valore della datatype: "avv." "Avv", "Prof. Ing.").  

Fatemi sapere cosa ne pensate.

[1] https://raw.githubusercontent.com/luigi-asprino/daf-ontologie-vocabolari-controllati/master/Ontologie/CPV/v0.7/CPV-AP_IT.rdf

**Comment by giorgialodi** [comment]
> Cerco di iniziare a sistemare gli issue che sollevo :-)

Grazie mille e ottimo!

> Ho fatto un fork del repository dove ho modellato una soluzione per risolvere questa issue.
> Ho aggiunto a CPV la classe:
> 
>     1. Title (che nella mia idea deve essere popolata con un vocabolario controllato di titoli/appellativi di una persona). Title ha un nome (il titolo, es. Avv.) e una lingua (permette di specificare vocabolari controllati rispetto a lingue diverse, es. it). Per modellare la lingua ho importato l'ontologia Language.

Ok, controllo questo punto: nelle altre ontologie che abbiamo fatto dove abbiamo usato vocabolari controllati, non abbiamo mai esplicitamente modellato la lingua da associare poi a una proprietà della classe. Questo perché nei vocabolari controllati usiamo skos e skos ha già nelle sue specifiche il fatto che la prefLabel è una per ogni possibile lingua. Tuttavia se il titolo cambia da nazione a nazione, come potrebbe essere in questo caso, allora penso che la strada da te presa sia la migliore.
L'unica cosa: non sarebbe meglio chiamarla PersonTitle oppure HonorificPrefix (come dice FOAF)? Così siamo sicuri non si confonda con altri concetti.

Una cosa importante: in OntoPIA una classe e/o proprietà che è legata a un vocabolario controllato viene annotata con una proprietà di l0, i.e., l0:controlledVocabulary seguita dall'URI del vocabolario controllato. 

>     2. La proprietà CPV:hasTitle permette di collegare una persona ad un suo titolo.
>        Trovate l'ontologia modificata qui [1].

Ok, ci guardo. Se cambiamo Title come suggerito sopra, possiamo di conseguenza rifattorizzare anche questa proprietà :)
> 
> 
> Ho pensato all'uso di un vocabolario controllato invece che una datatype property, per evitare che il valore della datatype fosse forzato (e.g. più titoli e/o formati diversi nel valore della datatype: "avv." "Avv", "Prof. Ing.").

Mi sembra un'ottima idea. Potremmo fare il vocabolario HonorificPrefix sotto a classifications-for-people.
Hai già gli elementi di questo possibile vocabolario così da iniziare anche su questo fronte?

Grazie @luigi-asprino 
> 
> Fatemi sapere cosa ne pensate.
> 
> [1] https://raw.githubusercontent.com/luigi-asprino/daf-ontologie-vocabolari-controllati/master/Ontologie/CPV/v0.7/CPV-AP_IT.rdf

**Comment by giorgialodi** [comment]
ah una cosa: fissati questi due punti di cui sopra, puoi tu stesso fare PR. Il processo prevede che lato nostro ci sia un controllo generale e se tutto è ok, la modifica viene recepita. 
Ho visto poi che hai fatto proprio una nuova versione e va benissimo.

**Comment by luigi-asprino** [comment]
D'accordo, l'ho chiamato PersonTitle (vorrei evitare di usare Prefix perché i titoli a volte si mettono anche come suffissi, come PhD, MD ecc.).

Ho eliminato la parte del linguaggio (non conoscevo la gestione dei vocabolari).

Avevo visto l'uso della proprietà l0:controlledVocabulary ma non avendo l'URI del vocabolario controllato  non l'ho aggiunta (per ora).

Quale processo usate per definire un controlledVocabulary? Cioè, capisco quello che devo definire: un identificativo, due label (una ita e una eng), due comment (uno ita e una eng). Non capisco bene la questione del rank che bisogna definire (dovrebbero essere tutti a livello 1 nel mio caso? i livelli più profondi si usano solo per vocabolari con tassonomie a più livelli?).

Gli export in altri formati li avete fatti direttamente da Protegè? O faccio push solo delle versioni RDF e poi li convertite voi?

**Comment by anuzzolese** [comment]
Si eviterei di chiamare la classe Title.
Tutti gli export sono stati fatti da Protégé.

**Comment by giorgialodi** [comment]
In questo issue, ormai chiuso, avevo spiegato tutto https://github.com/italia/daf-ontologie-vocabolari-controllati/issues/47.

Devo aggiungere questa descrizione nel readme all'inizio. Me lo segno da fare.

**Comment by luigi-asprino** [comment]
Creata una pull request per inserire queste modifiche in OntoPiA #60

**Comment by anuzzolese** [comment]
Fatto merge con la commit e19d866

**Comment by giorgialodi** [comment]
Grazie @luigi-asprino  Ho corretto gli URI dell'ontologia CPV perché protegé secondo me fa cose strane e l'aveva cambiato con l0. Ho anche rivisto il vocabolario controllato nei metadati per far sì che sia conforme a DCAT-AP_IT e ho rivisto i codici assegnati a ciascun valore. C'era un po' un mix di italiano e inglese. Tutti gli URI di ontopia sono in inglese e quindi per i casi di concetti solo disponibili in italiano non era possibile. Ho trasformato i codici in numeri incrementali. 
Ci sono solo un paio di dubbi: dott.ssa mi sa che in inglese sia tradotto in Dr comunque. Dobbiamo fare attenzione al punto finale per Dott., forse ci va ma non ne sono sicura.
