### ISSUE TITLE
Proprietà inversa mancante di involvesCulturalProperty in Cultural-ON

### ISSUE THREAD

**Issue by anuzzolese** [italia/daf-ontologie-vocabolari-controllati#62]
Avrebbe molto senso aggiungere la proprietà inversa di involvesCulturalProperty in Cultural-ON che è attualmente mancante.
In ArCo abbiamo bisogno di tale proprietà.

**Comment by giorgialodi** [comment]
Ciao @anuzzolese sì va bene. Finisco alcune cose e lo faccio subito. Ti informo quando fatto

**Comment by giorgialodi** [comment]
@anuzzolese pubblicata una revisione dell'ontologia Cultural-ON versione 3.2 con l'inserimento della proprietà inversa. Ho scelto di aggiornare la versione 3.2. Nei metadati (versionInfo) ci sono tutte le azioni fatte sulla versione 3.2 del 27 Maggio 2019 con anche il riferimento a questo issue.
Ho corretto anche alcuni import di altre ontologie che erano sbagliati.

Ricordo che, vista la disponibilità di un embrione (seppur piccolo) dell'ontologia dei progetti, è probabile che Cultural-ON debba essere allineata a quell'ontologia avendo al suo interno il concetto di Progetto culturale collegato con le altre classi principali di Cultural-ON.

**Comment by anuzzolese** [comment]
Perfetto.
Grazie Giorgia.
