### ISSUE TITLE
Cambio da cis a POI?

### ISSUE THREAD

**Issue by alechiaretti** [italia/daf-ontologie-vocabolari-controllati#64]
Se non sbaglio, con l'ultimo aggiornamento tutta l'ontologia cis è stato sostituito da POI.
Mi sono perso qualche cosa, o c'è stato qualche problema?

PS: non sono pratico di GitHub, spero che questo messaggio sia nel posto giusto.

**Comment by giorgialodi** [comment]
ciao @alechiaretti il posto è giustissimo! Per quanto riguarda CIS non mi è chiaro cosa intendi per sostituito da POI ma sicuramente la classe CIS è sottoclasse di POI. Comunque ricontrollo meglio perché a memoria non ricordo e ti indico meglio. Grazie

**Comment by giorgialodi** [comment]
@alechiaretti la versione RDF/XML è effettivamente POI. Non so cosa sia successo. La versione RDF-Turtle è corretta. Ora riallineo tutto e ti informo quando ho fatto. E' chiaramente un errore.

**Comment by giorgialodi** [comment]
ciao @alechiaretti ora dovrebbe essere tutto ok in tutte e tre le serializzazioni RDF per la versione 3.2 di cultural-on. Controlla anche tu per vedere se ti torna. Chiudo l'issue solo dopo aver ricevuto un tuo ok. Grazie mille.

**Comment by alechiaretti** [comment]
Si, adesso mi sembra tutto in ordine. Grazie

**Comment by giorgialodi** [comment]
Benissimo, allora chiudo l'issue. Grazie per la segnalazione.
