### ISSUE TITLE
Classificazione dei regolamenti comunali

### ISSUE THREAD

**Issue by marinabassu** [italia/daf-ontologie-vocabolari-controllati#73]
Salve,
all'interno della codifica dei documenti come posso classificare i regolamenti?

**Comment by giorgialodi** [comment]
Ciao @marinabassu, per capire meglio come aiutarti, mi puoi indicare precisamente il vocabolario a cui ti riferisci e che evidentemente non è chiaro a sufficienza?
Stiamo parlando del vocabolario sull'albo pretorio dei comuni o di quello più generale di [classificazione dei documenti pubblici](https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-documents/government-documents-types)? In quest'ultimo caso, un regolamento comunale a mio parere è sicuramente un atto normativo.

Spero di aver risposto alla domanda. Se no, se puoi fornirci più elementi vediamo di aiutarti meglio :)

**Comment by giorgialodi** [comment]
Ciao @marinabassu volevo capire se eravate riusciti a risolvere e quindi potevamo chiudere l'issue, oppure se avete ancora problemi, nel qual caso dovremmo agire opportunamente.

**Comment by marinabassu** [comment]
Ciao,
scusa ma solo due giorni fa abbiamo trovato una soluzione. I regolamenti li
abbiamo inseriti come sottocategoria di *Documenti funzionamento interno. *
Abbiamo però un problema sulla classificazione dei bandi di concorso e
altri bandi e avvisi (non considerati i bandi di gara). Non trovo
corrispondenza in nessuna delle macrocategorie.
Avete già preso in considerazione i bandi'?

Inoltre nelle tipologie di servizi non troviamo nessuna corrispondenza per
svariati servizi. Vi fornirò un elenco quando completiamo l'assegnazione.
Grazie
Marina.

Il Lun 18 Nov 2019, 15:34 giorgialodi <notifications@github.com> ha scritto:

**Comment by giorgialodi** [comment]
Ciao @marinabassu i bandi di gara, di concorso e avvisi vari di solito nei comuni sono pubblicati nell'albo pretorio. Pertanto secondo il vocabolario government-documents-types è un Documento dell'albo pretorio (https://w3id.org/italia/controlled-vocabulary/classifications-for-documents/government-documents-types/1). Per questa categoria esiste poi un vocabolario controllato dedicato a parte (https://w3id.org/italia/controlled-vocabulary/classifications-for-documents/municipal-notice-board).
In merito alle voci che indichi i seguenti URi possono essere utilizzati:
- Avviso https://w3id.org/italia/controlled-vocabulary/classifications-for-documents/municipal-notice-board/D-01
-Bando https://ontopia-lodview.prod.pdnd.italia.it/controlled-vocabulary/classifications-for-documents/municipal-notice-board/D-02 specializzato in bando di concorso (https://w3id.org/italia/controlled-vocabulary/classifications-for-documents/municipal-notice-board/D-02-01), bando di gara (https://w3id.org/italia/controlled-vocabulary/classifications-for-documents/municipal-notice-board/D-02-02) e bando di contributi e vantaggi economici (https://w3id.org/italia/controlled-vocabulary/classifications-for-documents/municipal-notice-board/D-02-03)  

Per quanto riguarda i servizi, fammi sapere che vedo di mapparli sulle tematiche individuate. Stiamo infatti parlando delle tematiche per i servizi giusto?

**Comment by cirospat** [comment]
> _Ciao, scusa ma solo due giorni fa abbiamo trovato una soluzione. I regolamenti li abbiamo inseriti come sottocategoria di *Documenti funzionamento interno._ * 

ciao @marinabassu 
scusami una riflessione:
i regolamenti non riguardano (soprattutto i regolamenti comunali) solo quello che tu chiami il "funzionamento interno" dell'ente.
Un regolamento comunale può regolamentare le attività su suolo pubblico o la mobilità su suolo pubblico, ad esempio.  Un regolamento può gestire attività interne dell'ente o esterne all'ente.
Credo sia importante questo approfondimento per rendere quanto più applicabile a tutti gli enti un vocabolario controllato.
Che ne pensi?

**Comment by marinabassu** [comment]
Ciao Giorgia,
volentieri... i regolamenti non riguardano solo la gestione interna. La
maggior parte riguardano quella esterna.. ma normativa forse non va bene.
Io ora sono ad un corso ma possiamo approfondire... a dopo

Il Mar 19 Nov 2019, 12:24 ciro spataro <notifications@github.com> ha
scritto:

**Comment by giorgialodi** [comment]
Ciao @marinabassu era @cirospat del Comune di Palermo che faceva la riflessione sui regolamenti :) e ringrazio Ciro per lo scambio che aiuta a migliorare quanto fatto.
Sinceramente mi trovo d'accordo con Ciro: i regolamenti secondo me è improprio attribuirli **solo** a meri documenti di funzionamento interno. Sono regole a tutte gli effetti che come diceva Ciro possono avere **anche** un impatto  sulla collettività.

Qui secondo me la riflessione è di questo tipo:
1. esistono **regolamenti interni** a una PA? Allora forse quelli potrebbero rientrare nella fattispecie di documenti che regolano il funzionamento interno;
2. esistono regolamenti che hanno un impatto sulla colelttività allora secondo me quelli sono atti normativi che danno regole, per esempio sulle attività svolte su suolo pubblico ecc., come ricordato da Ciro.

In altre classificazioni che ho visto, per esempio in Normattiva, **regolamento** è una voce prevista come tipologia di atto normativo.

**Comment by marinabassu** [comment]
Ciao Giorgia,
concordo anche io e spostiamo in blocco la sottosezione -Regolamenti- e
-Statuto- in normativa (va bene per interni ed esterni).
Per le altre criticità che ti ho segnalato preferisco affrontarle con te a
breve (dopo aver comopletato le assegnazioni delle tipologie a tutti i
servizi).

Grazie
Marina

Il giorno mer 20 nov 2019 alle ore 11:32 giorgialodi <
notifications@github.com> ha scritto:

**Comment by giorgialodi** [comment]
Ciao @marinabassu sono contenta abbiate trovato la quadra sui regolamenti con l'attuale vocabolario. A questo punto se per te va bene, chiuderei questo issue specifico sui regolamenti e nel caso ne aprirei un altro sulla classificazione dei servizi per le varie tematiche. Per giunta trovo molto utile fare queste cose pubblicamente perché possono essere d'ausilio anche ad altri Comuni (come il caso di @cirospat che ha aperto una riflessione in merito).

**Comment by cirospat** [comment]
grazie @giorgialodi e @marinabassu per l'approfondimento.
Scrivo una cosa che può aiutare la classificazione.

---
### Regolamenti = 
atti amministrativi che hanno efficacia all'interno e all'esterno dell'ente pubblico che li ha generati.

### Circolari =
 atti amministrativi che hanno efficacia all'interno **e non all'esterno** dell'ente pubblico che li ha generati.

---
Vado di semplicità :)

**Comment by giorgialodi** [comment]
Ciao @cirospat ah molto bene. Allora direi che risulta più facile classificarli. Comunque si era aperta la possibilità di fare un vocabolario dedicato per atti normativi, un po' come è stato fatto il vocabolario dedicato per l'albo pretorio. Questo potrebbe aiutare in futuro.

**Comment by marinabassu** [comment]
Ciao Giorgia, si possiamo chiudere con i regolamenti. Appena possibile
inserisco Bandi e tipologie di servizi. I bandi pur essendo pubblicati
all'albo (pubblcazione legale devono avere una sezione dedicata perchè va
gestito tutto il procedimento fino all'esito e l'albo non è la sezione
adatta (vedi Bandi di concorso e Gare d'appalto) in amministrazioen
trasparente.
Per la classifcazione dei documenti avete qualcosa da proporre per le
sottosezioni?

Marina

Il giorno mer 20 nov 2019 alle ore 11:57 giorgialodi <
notifications@github.com> ha scritto:

**Comment by marinabassu** [comment]
dimenticavo... avete inserito -Istanze- come macro sezioni di -Documenti- .
L'istanza è l'avvio di un procedimento da effettuarsi con diverse modalità
(in genere compilando un modulo cartaceo o online tramite un servizio
dedicato o altro).

Marina

Il giorno mer 20 nov 2019 alle ore 16:51 Marina Bassu <bassumarina@gmail.com>
ha scritto:

**Comment by giorgialodi** [comment]
Ciao @marinabassu ho bisogno di chiarire un paio di punti per poterti rispondere per bene. La questione bandi non mi è chiarissima. Certo i bandi di gara sono in amministrazione trasparente e ora in OntoPiA sono disponibili almeno tre vocabolari controllati e un'ontologia per la trasparenza che potrebbero essere d'aiuto (vocabolari: https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/classifications-for-transparency, ontologia: https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/Ontologie/Transparency).

Invece per la domanda che mi poni ovvero "_Per la classifcazione dei documenti avete qualcosa da proporre per le sottosezioni?_", intendi se abbiamo da proporre delle sotto voci delle macro voci incluse nel vocabolario sulla classificazione dei documenti? Se questa è la domanda, allora nel caso della voce "Documento albo pretorio" la risposta è sì e sono tutti le voci, a loro volta organizzate in gerarchia, del vocabolario controllato sull'albo pretorio di cui si parlava sopra. Per le altre voci non ancora.  C'è un lavoro ongoing per la voce "Atto normativo" di creazione di un vocabolario controllato specifico. Di fatto stiamo dicendo che alcune delle macro-voci qui riportate sulla classificazione dei documenti sono a loro volta vocabolari controllati con dignità a sé stante.

Invece, per il commento sull'istanza, intendi dire che l'istanza è un'azione e non un documento? Nel vocabolario istanza è definita come richiesta scritta fatta pervenire a una pubblica amministrazione. Non ti torna? 

Grazie Marina per questi scambi!

**Comment by marinabassu** [comment]
Ciao,
mi riferisco ad una sezione dedicata ai bandi, che raccoglie tutti (esempio
bando per iscrizione asilo nido, bando per contributi per la cultura, bando
per concessione impianti sportivi ecc.). L'albo pretorio  è consultabile
solo fino alla scadenza, avendo solo la funzione di pubblicità legale, ma
il bando non si conclude con la pubblicazione all'albo, segue tutta la fase
di istruttoria (quesiti, rettifica atti, garduatorie, esito) che vanno
raccolti in un unico contenitore (bando). Tutto questo andrebbe inserito
nella sezione documenti ma come macro.

* intendi se abbiamo da proporre delle* *sotto voci delle macro voci
incluse nel vocabolario sulla classificazione dei documenti?* SI ... quindi
possiamo condividere  eventuali sottosezioni

*sull'istanza, intendi dire che l'istanza è un'azione e non un documento?
SI *
*Nel vocabolario istanza è definita come richiesta scritta fatta pervenire
a una pubblica amministrazione.  * (modulo o form da compilare online o
altro è la modalità di avvio che va dentro il servizio specifico. Esempio
richiesta pass ZTL)

Marina

Il giorno mer 20 nov 2019 alle ore 17:10 giorgialodi <
notifications@github.com> ha scritto:

**Comment by giorgialodi** [comment]
Ciao @marinabassu , non credo che la classificazione di tutti i possibili bandi sia da macro voci di un possibile vocabolario sui tipi di documenti per le PA. Tra l'altro  guardando l'elenco che mi fai dei bandi, mi sembra che siano sempre dei bandi: cambia l'ambito tematico ma sempre bandi sono :) 
Invece per quel che riguarda i documenti che costituiscono l’iter di fatto, tipo graduatorie, esiti, ecc. che menzioni, dovrebbero rientrare nell’albo pretorio. Mi ricordo infatti che gli esiti di gara, o le graduatorie venivano pubblicate lì per i comuni e il più delle volte sono considerati avvisi e l’avviso è nel vocabolario controllato dell’albo pretorio.
Considera inoltre che nel vocabolario dei documenti generici c’è una voce piuttosto vasta che è documento (tecnico) di supporto che può essere utilizzata in quei casi perché è a supporto del processo complessivo che descrivi.

Certo che potete proporre delle sotto voci del vocabolario controllato sui tipi di documento. Consiglio di proporle qui a beneficio di tutti: se è un vocabolario condiviso è bene condividere tutti i passaggi :-) Tuttavia, quando è stato creato il vocabolario anche con alcuni ragazzi del Team si era detto di avere poche voci di primo livello demandando eventualmente ad altri vocabolari più specifici, così come abbiamo fatto per l’albo pretorio.

La presentazione dell’istanza è l’azione. Alcuni documenti che ho visto si chiamano proprio Istanza di accesso … sono moduli a dir il vero che poi vengono inviati per fare formalmente una richiesta (richiesta/istanza di solito sono usati come sinonimi). Anche nel vocabolario controllato sul tipo di input e output di un servizio pubblico abbiamo definito un’istanza/richiesta (https://ontopia-lodview.pdnd.italia.it/controlled-vocabulary/classifications-for-public-services/service-input-output/REQ).
Non ti torna? Se no potremmo usare un termine diverso ma vorrei sentire anche @gabrielefrancescotto che mi sa aveva  dato degli input su come formare il vocabolario.

**Comment by giorgialodi** [comment]
Questo issue è molto collegato all'issue #78 appena chiuso. E' stata applicata una variazione al vocabolario controllato dei tipi di documenti della PA. E' emerso il requisito di dettagliare alcune sue voci in ulteriori vocabolari controllati. Su questo ci proviamo a lavorare. Chiudo pertanto questo issue che in realtà era più riferito ai regolamenti comunali che mi sembra problematica risolta.
