### ISSUE TITLE
Invalid JSON: VocabolariControllati/theme-subtheme-mapping/theme-subtheme-mapping.json

### ISSUE THREAD

**Issue by jenkin** [italia/daf-ontologie-vocabolari-controllati#75]
Missing comma.

https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/1c06a7b9fd06d9971ff723f8172fcb19f361a430/VocabolariControllati/theme-subtheme-mapping/theme-subtheme-mapping.json#L1274

**Comment by giorgialodi** [comment]
It should be fixed.
