### ISSUE TITLE
Proposta cambio label in vocabolario government-document-types 

### ISSUE THREAD

**Issue by giorgialodi** [italia/daf-ontologie-vocabolari-controllati#78]
Proposta del comune di Cagliari:

Sostituire l'attuale label "Documento funzionamento interno" in "Atto di programmazione e gestione".

Personalmente, ripensandoci meglio, ho qualche dubbio: mentre nel primo caso la voce del vocabolario indica "i documenti relativi al funzionamento interno come per esempio rendimenti, rendiconti, procedure, bilanci consuntivi e preventivi", nella proposta di modifica  la voce sembra più ampia e andare in sovrapposizione con quanto poi un comune deve pubblicare nell'albo pretorio per cui esiste già una voce specifica del vocabolario. La gestione non è detto che sia interna, così come la programmazione non è detto che sia delle attività interne all'istituzione.

La voce "Documento funzionamento interno" voleva raccogliere tutte e sole le tipologie di documenti che riguardano il funzionamento del comune o della Pubblica Amministrazione specifica che fa uso del vocabolario. Tutto il resto, soprattutto per i comuni dovrebbe essere pubblicato all'interno dell'albo pretorio. 

Che ne pensate? @gabrielefrancescotto @cirospat @mamatteo @marinabassu @antoniopascalis @francescozaia e gli altri che vogliono contribuire alla discussione :)

**Comment by cirospat** [comment]
cara @giorgialodi 

il **`Documento funzionamento interno`** è un documento. Per documento si intende:
- nota
- determinazione
- deliberazione 
- decreto
- ordinanza
- ecc.

L' **`Atto di programmazione e gestione`** è un "Atto". Non sono un esperto di atti di programmazione e gestione, ma questa "categoria" mi sembra diversa dal "Documento di funzionamento interno".

Altra analisi: la "programmazione e la gestione" in una PA si attua con i "documenti di funzionamento interno". Mi spiego: La gestione delle attività di una PA si concretizza attraverso la redazione e sottoscrizione di atti amministrativi (deliberazioni, determinazioni, note, ecc.).

Ritengo - per la mia esperienza - che l'**`Atto di funzionamento interno`** è il tipo di documento più atomico di tutti dentro la PA per il funzionamento (cioè le deliberazioni, determinazioni, note, ecc.).
Mentre l'**`Atto di programmazione e gestione`** è costituito dalle varie tipologie di **`Documento funzionamento interno`**.
Non so se mi spiego in maniera chiara.
Comunque sono aperto ai confronti e alle analisi a più teste.

**Comment by MarinaGalluzzo** [comment]
Ciao @giorgialodi e @cirospat vi esprimo il mio pensiero.
Atto (o, meglio, documento) di programmazione e "documento di funzionamento interno" richiamano  documenti con funzione diversa... "Atto di programmazione" riguarda concettualmente  documenti con funzione programmatoria (strategica) quali Bilanci, programma lavori pubblici, programma di mandato, ecc.). Si  tratta comunque di documenti (strumenti) al servizio (o presupposto) dello svolgimento dei compiti istituzionali.
Esistono invece documenti di funzionamento interno veri e propri (strettamente intesi), quali il regolamento di organizzazione e gestione degli uffici, regolamento per incarichi extralavorativi dei dipendenti, codice di comportamento, ecc), ma non è possibile far rientrare l'intera categoria di regolamenti nel concetto di "documenti di funzionamento interno) poiché  trattasi di atti normativi (di secondo livello) di portata generale (regolamento edilizio, regolamento concessioni contributi, regolamento sicurezza e ordine pubblico, ecc). 
"Documento di gestione" potrebbe essere inteso in senso più ampio comprendendo sia la gestione organizzativa interna, sia la gestione delle attività rivolte all'esterno. 
Tutti questi "documenti" vanno comunque pubblicati all'albo pretorio (quantomeno attraverso la deliberazione che costituisce l'effettiva manifestazione di volontà dell'atto)

**Comment by giorgialodi** [comment]
Ciao @cirospat e @MarinaGalluzzo, come sempre grazie per la discussione. Ho riletto i vostri commenti e mi sembra di intuire comunque che un bilancio di previsione lo fareste ricomprendere in un generico "atto di programmazione" che poi successivamente con deliberazione viene pubblicato nell'albo pretorio. Facciamo allora esempi pratici:

Ho un **bilancio di previsione o altro tipo di bilancio**: come lo categorizzo con questo vocabolario generale? 
Soluzione 1: Con "Documento di Albo pretorio" e poi successivamente come "deliberazione" 
Soluzione 2: Con "Documento di funzionamento interno" (che è l'attuale label usata proprio per questi tipi di documenti)
Soluzione 3: Con una nuova voce da creare per meglio rappresentare questi documenti di strategia della PA "Atto di programmazione" (o altre etichette tipo "Documenti finanziari")

Ho un **regolamento gestione uffici:**: come lo categorizzo con questo vocabolario generale?
Soluzione 1: Con "Documento di Albo pretorio" e poi successivamente come deliberazione
Soluzione 2: Con "Documento di funzionamento interno" (che è l'attuale label usata proprio per questi tipi di documenti)
Soluzione 3: Con una nuova voce tipo "Atto di gestione" (da tenere distinta rispetto a un possibile "atto di programmazione o documenti finanziari")

Ho un **verbale o rendiconto**: come lo categorizzo con questo vocabolario generale?
Soluzione 1: Con "Documento di Albo pretorio" e poi successivamente come "Deliberazione" oppure "Avviso" o altro
Soluzione 2: Con "Documento di funzionamento interno" (che è l'attuale label usata proprio per questi tipi di documenti)
Soluzione 3: Con una nuova voce tipo "Atto di gestione" (da distinguersi rispetto a un possibile "atto di programmazione o documenti finanziari")

Mi aiutate rispetto ai vostri punti di vista a capire meglio? Ovviamente la cosa è aperta a tutti quelli di questo thread e a tutti quelli interessanti a darci una mano per migliorare il vocabolario :)

**Comment by cirospat** [comment]
> Mi aiutate rispetto ai vostri punti di vista a capire meglio?

Secondo me un atto (esempio: `verbale`, `regolamento gestione uffici`, `un bilancio di previsione`) può essere ricompreso in più categorie ("**Documento di Albo pretorio**" - "**Documento di funzionamento interno**" - "**Atto di gestione**").

**Comment by MarinaGalluzzo** [comment]
Ciao @giorgialodi @cirospat Rispondo per punti, ma metterò sul piatto altre tipologie di atti, affinché si possa ricercare la migliore definizione... 

> Ciao @cirospat e @MarinaGalluzzo, come sempre grazie per la discussione. Ho riletto i vostri commenti e mi sembra di intuire comunque che un bilancio di previsione lo fareste ricomprendere in un generico "atto di programmazione" che poi successivamente con deliberazione viene pubblicato nell'albo pretorio.

Sull'albo pretorio condivido quanto aveva già espresso su slack Marina Bassu: Albo pretorio è un adempimento e un po' tutto "passa" (per un tempo limitato) dall'albo pretorio. In tal senso la categoria Documento di Albo pretorio -per i siti web -  la interpreterei come categoria residuale. Invece condividerei un'ipotetica voce "atto di programmazione" (ma vedi appresso) 

 Facciamo allora esempi pratici:
> 
> Ho un **bilancio di previsione o altro tipo di bilancio**: come lo categorizzo con questo vocabolario generale?
> Soluzione 1: Con "Documento di Albo pretorio" e poi successivamente come "deliberazione"
> Soluzione 2: Con "Documento di funzionamento interno" (che è l'attuale label usata proprio per questi tipi di documenti)
> Soluzione 3: Con una nuova voce da creare per meglio rappresentare questi documenti di strategia della PA "Atto di programmazione" (o altre etichette tipo "Documenti finanziari")
> 
A mio avviso sarebbero valide sia la soluzione 2 che  3. Ma per una risposta puntuale  rilancio con altra domanda: 
Come classifico (ragionando di sito web) atti quali: 
- Bilancio sociale (rendiconto tipico - su base volontaria - per i cittadini). L'atto NON è documento di albo pretorio, né di funzionamento interno.
- Bilancio di mandato (rendiconto politico - in quanto tale rivolto ai cittadini). Dalle definizioni proposte personalmente sceglierei "documento di funzionamento interno", ma sarebbe una forzatura.
Un'ulteriore classificazione del tipo "documento di programmazione e rendicontazione" chiarirebbe a mio avviso la classificazione per questa tipologia di atti, a cui si aggiungerebbero, a mio avviso : Programma lavori pubblici, Documento Unico di programmazione, Relazione annuale Responsbaile anticorruzione (che, di fatto, è un rendiconto), documenti del ciclo della Performance, report questionari citizen satisfaction (qualora pubblicati)
- 
> Ho un **regolamento gestione uffici:**: come lo categorizzo con questo vocabolario generale?
> Soluzione 1: Con "Documento di Albo pretorio" e poi successivamente come deliberazione
> Soluzione 2: Con "Documento di funzionamento interno" (che è l'attuale label usata proprio per questi tipi di documenti)
> Soluzione 3: Con una nuova voce tipo "Atto di gestione" (da tenere distinta rispetto a un possibile "atto di programmazione o documenti finanziari")

Riterrei appropriato Documento di funzionamento interno. Se invece si dovesse trattare ad esempio di Regolamento dei Contratti o del Regolamento per i referendum consultivi riterrei una forzatura classificarlo "Documento di funzionamento interno" e opeterei per "Atti normativi" (ma la descrizione  data alla definizione mi pare non preveda gli atti atti normativi di secondo grado, quali i regolamenti..)
> 
> Ho un **verbale o rendiconto**: come lo categorizzo con questo vocabolario generale?
> Soluzione 1: Con "Documento di Albo pretorio" e poi successivamente come "Deliberazione" oppure "Avviso" o altro
> Soluzione 2: Con "Documento di funzionamento interno" (che è l'attuale label usata proprio per questi tipi di documenti)
> Soluzione 3: Con una nuova voce tipo "Atto di gestione" (da distinguersi rispetto a un possibile "atto di programmazione o documenti finanziari")
Per quanto ho espresso sopra riterrei più funzionale una eventuale voce "documenti di programmazione e rendicontazione" (anziché finanziari). In assenza, opterei per documento di funzionamento interno
Invece una eventuale voce tipo "atto di gestione" mi appare eccessivamente generica comprendendo un po' tutto.
Questo il mio punto di vista, ma sarebbe importante capire cosa ne pensano altri ...
> 
> Mi aiutate rispetto ai vostri punti di vista a capire meglio? Ovviamente la cosa è aperta a tutti quelli di questo thread e a tutti quelli interessanti a darci una mano per migliorare il vocabolario :)

**Comment by giorgialodi** [comment]
Ciao a tutti,

ritorno sul punto con questa proposta pratica di revisione del vocabolario sui tipi di documenti:

1) **Documento Albo Pretorio** (attuale definizione)
2) **Modulistica** (attuale definizione)
3) **Documento di funzionamento interno** (Rientrano in questo concetto tutti i documenti relativi al mero funzionamento interno come per esempio regolamento gestione uffici, note varie attinenti al funzionamento interno dell'ente)
4) **Atto normativo** (Rientrano in questo concetto tutte le tipologie di atti normativi quali per esempio la costituzione, il decreto legislativo, il decreto legge, il decreto reale, il regio decreto ma anche regolamento dei contratti,  regolamento per i referendum consultiv, ecc.)
5) **Documento di programmazione e rendicontazione** (Rientrano in questo concetto tutte quelle tipologie di documenti relativi alle attività di programmazione e rendicontazione. A titolo d'esempio rientrano documenti quali: bilanci, programma lavori pubblici, documento unico di programmazione, relazione annuale responsbaile anticorruzione, documenti del ciclo della performance, ecc.)
6) **Accordo tra enti** (attuale definizione)
7) **Documento attività politica** (attuale definizione)
8) **Documento (tecnico) di supporto** (attuale definizione)
9) **Istanza** (attuale definizione)

@MarinaGalluzzo negli atti normativi ci sono anche i regolamenti, non li avevo esplicitati nella definizione, erano negli ecc. :) In pratica sono le tipologie che ora usa per esempio Normattiva

Come dice poi @cirospat ci sono documenti che possono appartenere anche a più categorie come anche lui sopra ha evidenziato.

Se non avete problemi specifici procedo con applicare questa modifica, includendo le nuove definizioni ove necessario (cc @gabrielefrancescotto @marinabassu @antoniopascalis @francescozaia)

**Comment by MarinaGalluzzo** [comment]
Ciao Giorgia e tutti,
condivido la proposta
Un saluto a tutti
Marina


Il giorno mer 4 mar 2020 alle ore 09:57 giorgialodi <
notifications@github.com> ha scritto:

**Comment by giorgialodi** [comment]
Cambiamenti applicati. Chiudo questo issue. Qualora altri cambiamenti dovessero essere necessari, apriremo un altro issue.
