### ISSUE TITLE
Errore nel vocabolario trasparenza

### ISSUE THREAD

**Issue by deligios** [italia/daf-ontologie-vocabolari-controllati#83]
> daf-ontologie-vocabolari-controllati/VocabolariControllati/classifications-for-transparency/transparency-titulus
> 15.09	Servizi erogati	Services provided	IBAN e pagamenti informatici

Al capitolo 5, penultimo paragrafo, delle Linee guida è scritto:
> Inoltre, si precisa  che  per  evitare  che  gli  utenti  possano eseguire dei bonifici non integrato con il Sistema pagoPA,  e'  fatto divieto ai  soggetti  tenuti  per  legge  all'adesione  a  pagoPA  di pubblicare in qualsiasi modo l'IBAN di accredito. 

La citazione dell'IBAN è stata rimossa dall'art. 5 del CAD dal Dlgs 26-08-2016, n.179

Per errore, nella tabella dell'allegato A al Decreto legislativo 14-03-2013, n. 33, è stato lasciato il titolo vecchio.

Si propone di rinominare la voce in **Pagamenti informatici**

Segnalo inoltre che le voci del file daf-ontologie-vocabolari-controllati/VocabolariControllati/classifications-for-transparency/transparency-titulus/README.md hanno una numerazione disallineata rispetto al file csv

**Comment by giorgialodi** [comment]
Grazie @deligios, prendo in carico queste due cose.

**Comment by giorgialodi** [comment]
@deligios la questione dell'IBAN era nell'articolo 5 del CAD comma 3, 3-bis, 3-ter che sono stati abrogati? Puoi confermare? Hai per caso riferimento a com'erano questi commi prima della loro abrogazione?

**Comment by deligios** [comment]
@giorgialodi no, si trattava dell'art. 5 comma1:

- [Questa la versione pre-modifica](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005-03-07;82~art5!vig=2016-09-13)
- [Questa la versione post-modifica](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005-03-07;82~art5!vig=2016-09-14)
- [Questa la versione vigente](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005-03-07;82~art5!vig=)

**Comment by giorgialodi** [comment]
grazie @deligios non visualizzo i link e non so perché ma ho capito il punto e ora mi è tutto più chiaro! Procediamo alla modifica come suggerisci. Lasceremo una label alternativa nel caso qualcuno sollevi l'eccezione che nella tabella del 33/2013 c'è ancora quella dicitura ma la label ufficiale sarà quella che suggerisci.

**Comment by deligios** [comment]
curioso, io li vedo correttamente

**Comment by deligios** [comment]
Comunque ho segnalato l'errore nella tabella del dlgs 33 anche a Giuseppe Virgone

**Comment by giorgialodi** [comment]
@deligios ora li vedo! Forse sono stata sfortunata prima con normattiva che non rispondeva. Capita! Hai fatto bene a segnalare che ancora la tabella indica una dicitura non più coerente con le disposizioni normative.

**Comment by giorgialodi** [comment]
ciao @deligios è stato risolto con il merge della PR #82 Grazie per il supporto!
