### ISSUE TITLE
Diversy typos in public-event-types

### ISSUE THREAD

**Issue by deligios** [italia/daf-ontologie-vocabolari-controllati#84]
daf-ontologie-vocabolari-controllati/VocabolariControllati/public-event-types/

- Maniferstazione
- Defnizione_ITA
- spercifiche
- musiciali
- Ceremonies (in Label_3_livello_alternativa_2)
- Dialogue (in Label_3_livello_alternativa_2)
- epersti
- Experts (in Label_3_livello_alternativa_2)
- cominità
- Siflate
- Mecarti
- pubbico
- sicoperi
- Ex

**Comment by giorgialodi** [comment]
Grazie @deligios ricontrollo.

**Comment by deligios** [comment]
c'è anche un _Marcato_ che dovrebbe essere _Mercato_

**Comment by giorgialodi** [comment]
@deligios li ho individuati, che poi ragionavo, doveva proprio essere il messaggio dei typo visto anche il titolo. Ahahaha :D 
Solo un chiarimento: la segnalazione sulle parole in inglese per la label alternativa 3 è perché è in alcuni casi in inglese e in altri casi in italiano?

**Comment by deligios** [comment]
> la segnalazione sulle parole in inglese per la label alternativa 3 è perché è in alcuni casi in inglese e in altri casi in italiano?

Esatto

**Comment by giorgialodi** [comment]
ciao @deligios, i typo sono stati tutti corretti, tranne "Ex" che non mi è chiaro cosa volessi dire. Ho fatto una ricerca ma non ho trovato problemi. Per quel punto, a cosa ti riferivi nello specifico? Risolto quest'ultimo punto, chiudo poi l'issue.

**Comment by deligios** [comment]
Ho cercato anch'io, ma non l'ho più trovato. Forse era un ritaglio della mia elaborazione pre-caricamento in banca dati. Approfitto per segnalare che alcuni degli errori erano ricorrenti in più voci.

**Comment by giorgialodi** [comment]
Buongiorno @deligios sì nel CSV per forza. Dovrei averli sistemati però ora con il commt di ieri sera. Nell'RDF per ovvi motivi non erano ricorrenti. Chiudo issue; se per caso vedi altri problemi lo riapriamo tranquillamente :)
