### ISSUE TITLE
In transparency-titulus.csv manca la voce "Pagamenti dell'amministrazione"

### ISSUE THREAD

**Issue by deligios** [italia/daf-ontologie-vocabolari-controllati#85]
Prevista nella tabella di cui al [Decreto legislativo 14-03-2013, n. 33 all. A, art. 1](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2013-03-14;33:1~art1!vig=)

**Comment by giorgialodi** [comment]
Ciao @deligios, come avrai notato dalle PR di questo repo, stiamo rivedendo quel vocabolario, anche per includere quanto riporti.

**Comment by giorgialodi** [comment]
Ciao @deligios anche questo è stato risolto con il merge della PR #82. Grazie anche in questo caso per il supporto!
