### ISSUE TITLE
[MU-AP_IT] - annotations mancanti per la classe Value

### ISSUE THREAD

**Issue by fbuciuni90** [italia/daf-ontologie-vocabolari-controllati#87]
Ciao,

ho notato che mancano le annotation properties comuni (rdfs:label, rdfs:comment, ecc..) per la classe [Value](https://w3id.org/italia/onto/MU/Value) dell'ontologia [MU-AP_IT](https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/Ontologie/MU) in analogia con le altri classi e proprietà.

Grazie.

**Comment by giorgialodi** [comment]
Ciao @fbuciuni90  sì vero! Provo a inserirlo subito nella versione 0.3 (perchè non c'è alcun cambiamento nella semantica dell'ontologia)

**Comment by giorgialodi** [comment]
Ciao @fbuciuni90 con l'ultima commit tracciata dovrebbe essere a posto. Siccome per questa ontologie sono stati fatti degli schemi in Graffoo, ho aggiunto un readme con gli schemi stessi. L'ontologia è molto semplice ma vedo se riesco a fare cose analoghe pian piano anche con altre ontologie.
