### ISSUE TITLE
[IoT-AP_IT] - ObservationValue restriction issue

### ISSUE THREAD

**Issue by fbuciuni90** [italia/daf-ontologie-vocabolari-controllati#89]
Ciao,

credo che ci sia un typo nella definizione della classe **ObservationValue** dell'ontologia IoT-AP_IT.
In particolare, consedirando le restrictions
```
:ObservationValue rdf:type owl:Class ;
                  rdfs:subClassOf muapit:Value ,
                                  [ rdf:type owl:Restriction ;
                                    owl:onProperty :isObservationValueOf ;
                                    owl:someValuesFrom :Observation
                                  ] ,
                                  [ rdf:type owl:Restriction ;
                                    owl:onProperty :isValueForObservationParameter ;
                                    owl:someValuesFrom :ObservationValue
                                  ] ;
```
la class description della restriction sulla proprietà **isValueForObservationParameter** dovrebbe essere **ObservationParameter** e non **ObservationValue**.
Cosa ne pensate?

Grazie.

**Comment by giorgialodi** [comment]
Ciao @fbuciuni90 eh sì penso tu abbia ragione. Correggo appena riesco. Grazie mille!

**Comment by giorgialodi** [comment]
Risolto con l'ultimo commit. Grazie per la segnalazione!
