### ISSUE TITLE
Vocabolario controllato sui ruoli accademici italiani: proposta di inserimento

### ISSUE THREAD

**Issue by gpirrotta** [italia/daf-ontologie-vocabolari-controllati#91]
Salve a tutti
ho notato che nel vocabolario controllato sui ruoli accademici italiani manca il ruolo di **Professore Aggregato**.
Esso è disciplinato dall'**[art.6 comma 4 della legge 240/2010](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2010-12-30;240!vig=)** ed è attribuito a coloro a cui sono affidati, con il loro consenso e fermo restando il rispettivo inquadramento e trattamento giuridico ed economico, corsi e moduli curriculari compatibilmente con la programmazione didattica definita dai competenti organi accademici nonché compiti di tutorato e di didattica integrativa.

Tale titolo spetta ai ricercatori a tempo indeterminato, agli assistenti del ruolo ad esaurimento e ai tecnici laureati di cui all'articolo 50 del decreto del Presidente della Repubblica 11 luglio 1980, n. 382, che hanno svolto tre anni di insegnamento ai sensi dell'articolo 12 della legge 19 novembre 1990, n. 341, e successive modificazioni, nonché ai professori incaricati stabilizzati.

Ad essi e' attribuito il titolo di professore aggregato per l'anno accademico in cui essi svolgono tali corsi e moduli. Il titolo è conservato altresì nei periodi di congedo straordinario per motivi di studio di cui il ricercatore usufruisce nell'anno successivo a quello in cui ha svolto tali corsi e moduli. Ciascuna università, nei limiti delle disponibilità di bilancio e sulla base di criteri e modalità stabiliti con proprio regolamento, determina la retribuzione aggiuntiva dei ricercatori di ruolo ai quali, con il loro consenso, sono affidati moduli o corsi curriculari.

Per i motivi sopraindicati suggerisco di inserire il ruolo di Professore Aggregato all'interno del vocabolario controllato.

**Comment by giorgialodi** [comment]
Ciao @gpirrotta, ci siamo consultati con il gruppo di lavoro che abbiamo attualmente in essere con Regione Toscana per lo sviluppo in OntoPiA dell'ontologia HER (Higher Education and Research) e i relativi vocabolari controllati tra cui questo che menzioni.  I ruoli che sono stati per ora inseriti sono i ruoli cardine del processo di reclutamento all'interno delle università. Infatti, anche guardando la definizione da te riportata sembra che un professore aggregato sia un ulteriore ruolo che si aggiunge solo se si possiede uno dei ruoli da te citati quali ricercatore a tempo indeterminato, assitente di ruolo, ecc. che sono già inseriti nel vocabolario. In altri termini, questo vocabolario sui ruoli accademici individua i ruoli per il processo di reclutamento e non ruoli aggiuntivi che si può assumere. In ogni caso, per essere il più possibile precisi abbiamo pensato di agire in questo modo:

1. chiedere un parere a USTAT;
2. a valle del chiarimento di USTAT, che speriamo di ricevere quanto prima, specificare meglio l'obiettivo del vocabolario nella sua metadatazione

Ci riaggiorniamo quindi sul punto.
Grazie mille per il messaggio!

**Comment by giorgialodi** [comment]
Ciao @gpirrotta, torno da te su questo punto. Come riportato abbiamo contattato diversi esperti di dominio e solo in questi giorni abbiamo avuto risposte chiare che ci consentono di definire un po' meglio rispetto ad ora l'obiettivo di questo vocabolario controllato.
Grazie al supporto di alcuni esperti del MUR (Ministero Università e Ricerca), con questo vocabolario stiamo definendo i ruoli accademici (da intendersi come posizioni o figure della carriera universitaria, riferita alle attività di ricerca e didattica, a cui si accede tramite procedure concorsuali) definiti nell'ambito italiano [dal Ministero dell'Istruzione e Ministero dell'Università e della Ricerca](https://www.miur.gov.it/reclutamento-nelle-universita).

Alla luce di tale definizione non vengono inclusi nel vocabolario titoli aggiuntivi che possono essere attribuiti a figure che svolgono già funzioni accademiche, quali il “titolo” di Professore Aggregato, previsto dapprima dalla Legge 4 novembre 2005, n. 230, art. 1, c. 11, successivamente dalla Legge 30 dicembre 2010, n. 240, art. 6, c. 4.

In sostanza, Professore Aggregato sembra un titolo che assumi quando sei già in una delle posizioni che il vocabolario mira a individuare.

Cercheremo nelle definizioni di essere più chiari su questi ruoli con la connotazione prima indicata e tenendo conto del sistema MUR di cui sopra. Pertanto, il vocabolario subirà a breve un aggiornamento.

Tutto il gruppo di sviluppo dell'attuale ontologia HER di OntoPIA ti vuole ringraziare per questo commento prezioso che ci ha consentito di migliorare ulteriormente quanto già prodotto.
