### ISSUE TITLE
Non riesco ad accedere all'ontologia dei parcheggi

### ISSUE THREAD

**Issue by marcofromsicily** [italia/daf-ontologie-vocabolari-controllati#93]
Non riesco ad aprire questa url:

https://w3id.org/italia/onto/PARK

**Comment by giorgialodi** [comment]
Ciao @marcofromsicily, grazie per il commento. 
Se intendi che non riesci più a dereferenziare l'URI dell'ontologia via HTML, sì hai ragione, è un problema a noi noto.
In sostanza, tutta la parte di visualizzazione di OntoPiA via web mediante software come LODE, WebOWL e LodView è al momento non funzionante. L'infrastruttura era prima ospitata da PagoPA SPA nel contesto della Piattaforma Digitale Nazionale Dati (ex DAF). Ora è in mano ad AgID che sta proprio in questi giorni mettendo in piedi l'infrastruttura. Il periodo non aiuta molto a essere veloci in questa operazione, ma penso che presto ritornerà tutto come prima (su nuova infrastruttura però). Non so quantificare i tempi perché ci sono operazioni di cui non ho il controllo diretto.
Tuttavia, il meccanismo di content negotiation dovrebbe però essere comunque in piedi perché quello passa, se ricordo bene la configurazione che facemmo alcuni anni fa, attraverso i file raw presenti su github. Quindi da un punto di vista tecnico, utilizzando l'URI dovresti essere in grado di ottenere comunque il file sorgente.

Spero questo chiarisca la situazione.

**Comment by giorgialodi** [comment]
Ciao @marcofromsicily, ora tutto dovrebbe funzionare :) Fai una prova anche tu. Tutte le ontologie e i vocabolari hanno URI dereferenziati su nuova piattaforma AGID e sono quindi di nuovo navigabili online via html. Ci sono anche delle novità in queste nuove configurazioni: per esempio se usi https://w3id.org/italia/onto/PARK nella pagina web che ti comparirà ci sarà anche un link a Webvowl e puoi navigare la stessa anche attraverso una rappresentazione grafica a grafo.
