### ISSUE TITLE
possibile bug di transcodifica dagli archivi ISTAT dei comuni

### ISSUE THREAD

**Issue by ioggstream** [italia/daf-ontologie-vocabolari-controllati#94]
## Mi aspetto

che il VC dei comuni usi `skos:prefLabel` invece usa `skos:preflabel` minuscolo.

da verificare il meccanismo di transcodifica https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/territorial-classifications/cities

**Comment by giorgialodi** [comment]
E' un bug, la label deve essere skos:prefLabel. Lo correggo.

**Comment by ioggstream** [comment]
@giorgialodi hai risolto con cerca-trova o facendo un rebuild dei file originari?

**Comment by giorgialodi** [comment]
Il rebuild purtroppo per quel file non è possibile al momento perché era costruito all'interno del DAF che ormai non esiste più. Al momento ho solo corretto l'errore. Bisogna ripensare al rebulld di quel file. Avrei una soluzione ma richiede risorse di cui personalmente non dispongo.

**Comment by ioggstream** [comment]
Possiamo chiedere ai dataninja se vogliono divertirsi a fare una pipeline con circleci o gh-actions?

**Comment by giorgialodi** [comment]
Ci vuole però la pipeline di trasformazione in RDF prima :)
