### ISSUE TITLE
Derefenziazione Cultural ON

### ISSUE THREAD

**Issue by luigi-asprino** [italia/daf-ontologie-vocabolari-controllati#95]
Ciao,

vorrei importare Cultural-ON ma sembra che la dereferenziazione non funziona.
Sto tentando con le IRI:
- http://dati.beniculturali.it/cis/3.2
- http://dati.beniculturali.it/cis
Ma ricevo sempre la risposta ``#Empty Turtle``

**Comment by giorgialodi** [comment]
ciao @luigi-asprino ma intendi la dereferenziazione o la content negotiation?

Perché nei casi di ontologie i cui URI sono di altre PA, e quindi non seguono il pattern di OntoPiA con w3id.org/italia/onto non vengono da noi gestiti in termini di dereferenziazione e content negotation. Qui i meccanismi di content negotation e URI dereferentiation funzionano solo se gli URI sono scritti come indicato nella [sezione wiki relativa](https://github.com/italia/daf-ontologie-vocabolari-controllati/wiki#politica-di-gestione-degli-URI)

Se nel browser metto http://dati.beniculturali.it/cis in effetti riesco a leggere l'ontologia via HTML (via Lodview) su piattaforma però MIBACT.

**Comment by luigi-asprino** [comment]
Ciao @giorgialodi 

in realtà intendevo entrambi perchè non ho nessuna risposta :-) 

Ho visto che il browser risponde, ma mi aspetto anche una risposta alle richieste GET all'indirizzo http://dati.beniculturali.it/cis
Se non sbaglio, facendo una GET all'indirizzo di una ontologia dovrei ricevere l'intera ontologia in una serializzazione RDF, no? 
Questo mi sembra non succeda per Cultural-ON, cioè facendo richieste 
```
curl http://dati.beniculturali.it/cis
curl http://dati.beniculturali.it/cis/
curl http://dati.beniculturali.it/cis/3.2
curl http://dati.beniculturali.it/cis/2.0
```
Non ottengo nessuna risposta. 
Questo fa si che ad esempio gli import in protege non funzionino bene (o forse sbaglio qualcosa io? boh). 

Comunque provo allora contattare il MiBACT chiedendo spiegazioni a riguardo e chiudo questa issue in quanto non è un problema di OntoPiA.
Grazie

Un saluto

**Comment by giorgialodi** [comment]
E sì in OntoPiA questo funziona perché abbiamo implementato questo meccanismo via w3id.org. Bisogna capire se lato MIBACT hanno fatto una cosa simile. A quanto pare no, ma noi non la possiamo controllare a meno che non ci sia una volontà del MIBACT di migrare verso URI quali w3id.org/italia/onto. A quel punto avresti tutto come tutti gli altri casi delle ontologie OntoPiA. Potresti chiedere anche questo al MIBACT, se vogliono fare anche un passaggio simile.

**Comment by luigi-asprino** [comment]
La dereferenziazione sembra che sia sistemata ora.
Tuttavia sembra che ci sia un problemino quando si importa l'ontologia su Protege. Se sviluppando un'altra ontologia importo Cultural-ON questa non viene correttamente importata.
Un po' di prove fatte dal tecnico MiBACT hanno evidenziato che il problema risiede nel fatto che l'individuo che identifica l'ontologia (cioè ``<http://dati.beniculturali.it/cis>`` ) ha la proprietà ``rdfs:isDefinedBy``, cioè a quanto pare questa tripla crea problemi:
```
<http://dati.beniculturali.it/cis> rdfs:isDefinedBy <http://dati.beniculturali.it/cis>  .
```
Si può eliminare?

**Comment by giorgialodi** [comment]
Sì può fare tutto, ma che problema è? Cioè è il rdfs:isDefinedBy definito nell'ontologia p in tutti gli elementi dell'ontologia? Perché è così in tutte le altre ontologie di OntoPiA e non mi sembra crei problemi con gli import in Protégé. Ne sai di più?

**Comment by luigi-asprino** [comment]
infatti sembra strano anche a me.

Ti dico quello che ho fatto.
1. Creo una nuova ontologia in Protege
2. Aggiungo import http://dati.beniculturali.it/cis
E l'ontologia non viene importata

Nel log di Protege l'unico warning che vedo è il seguente:

```
   WARN  10:43:47  Imported ontology has unexpected id. During imports processing we anticipated OntologyID(OntologyIRI(<http://dati.beniculturali.it/cis>) VersionIRI(<http://dati.beniculturali.it/cis/3.2>))
```

Stessa cosa se invece di importarlo tramite l'iri ( http://dati.beniculturali.it/cis) importo l'ontologia scaricando il file.


invece se:
1. scarico il file
2. elimino rdfs:isDefinedBy
3. importo l'ontologia come file 
 l'ontologia viene importata correttamente

**Comment by giorgialodi** [comment]
ma elimini quale rdfs:isDefinedBy? Quello definito per ciascun elemento o quello iniziale più generale? Giusto per capire come intervenire. Comunque provo anch'io in Protégé e ti faccio sapere. Non ricordo di aver avuto questi problemi in passato.

**Comment by luigi-asprino** [comment]
Rimuovo solo quello associato all'individuo ontologia, cioè la tripla

```
<http://dati.beniculturali.it/cis> rdfs:isDefinedBy <http://dati.beniculturali.it/cis>  .
```

Allego anche il file modificato

[cis.owl.zip](https://github.com/italia/daf-ontologie-vocabolari-controllati/files/5589008/cis.owl.zip)

**Comment by luigi-asprino** [comment]
Non è detto che sia un problema dell'ontologia, magari sbaglio qualcosa io o la sbaglia protege

**Comment by giorgialodi** [comment]
Ok, allora facciamo così: provo più tardi (ora sono nel mezzo di alcuni lavori ma entro la giornata lo faccio) a ripetere i tuo i passi con Protégé e ti faccio sapere. Ah, che versione di Protégé usi? Perché sugli import si impazzisce sempre un po' e bisogna "martellare" :) 
Se vedo che la cosa non va allora provo a togliere quella tripla nell'individuo dell'ontologia. Una domanda: questa cosa che togliendo quella tripla va e con non va succedeva anche prima dell'intervento del MIBACT?

**Comment by luigi-asprino** [comment]
Protege 5.5.0 in locale

Prima se inserivo http://dati.beniculturali.it/cis non ottenevo proprio niente.
Inserendo l'indirizzo diretto del file raw [1] su github sono riuscito ad importare l'ontologia.

[1] https://raw.githubusercontent.com/italia/daf-ontologie-vocabolari-controllati/master/Ontologie/Cultural-ON/v3.2/Cultural-ON-AP_IT.rdf

**Comment by giorgialodi** [comment]
Ok per Protégé, è la mia stessa versione e penso sia l'ultima più stabile dove hanno sistemato diverse cose con gli import. 
"_Inserendo l'indirizzo diretto del file raw [1] su github sono riuscito ad importare l'ontologia._" --> Questo prima dell'intervento del MIBACT, ho capito bene? E senza togliere rdfs:isDefinedBy o togliendolo comunque?

**Comment by luigi-asprino** [comment]
Senza toglierlo.

**Comment by giorgialodi** [comment]
Ok allora forse il problema non risiede in quella proprietà :) Bisogna forse capirne un po' di più lato MIBACT temo. Lasciamo aperto l'issue. Io comunque provo e ti faccio sapere e informiamo il MIBACT che prendendo il file diretto da github qui le cose vanno bene.

**Comment by giorgialodi** [comment]
CIao @luigi-asprino ho provato ad aprire in Protégé da URL con http://dati.beniculturali.it/cis l'ontologia e me la apre regolarmente. Quindi non vedo il problema. 
Continui ad averlo?
L'unica cosa occhio che Protégé cambia l'URI dell'ontologia e quindi devi stare attento lì. Tuttavia tutte le classi e proprietà sono correttamente caricate. Ho questo messaggio da console "Loading for ontology and imports closure successfully completed in 15077 ms"

Fammi sapere se persiste.

**Comment by luigi-asprino** [comment]
Ciao,

grazie, ma il mio problema era con l'import.
Prova a creare una nuova ontologia (anche vuota) e importare http://dati.beniculturali.it/cis 
(Magari è solo un problema locale che ho sul mio pc)

**Comment by giorgialodi** [comment]
Ciao @luigi-asprino , ok ho fatto le seguenti prove:

1) ho provato direct import direttamente dentro protégé. Non me la carica e mi dà un Warning (non un errore) sull'ontology IRI
2) ho provato a creare con un editor di testo qualunque una nuovissima ontologia che ho chiamato pippo che fa solo una cosa, 
```
<https://w3id.org/italia/onto/pippo> rdf:type owl:Ontology ;
                                     owl:versionIRI <https://w3id.org/italia/onto/pippo/0.1> ;
                                     owl:imports <http://dati.beniculturali.it/cis> .
```

Me la importa correttamente e nella sezione direct import di protege vedo tutte le ontologie importate.

A questo punto non so bene. Potrebbe essere un problema di protégé stesso nel solo caso 1)? Hai provato a fare come nel mio secondo caso?

**Comment by luigi-asprino** [comment]
si si  funziona.

Per 1) penso che anche a te esca il warning che citavo qualche messaggio fa

```
   WARN  10:43:47  Imported ontology has unexpected id. During imports processing we anticipated OntologyID(OntologyIRI(<http://dati.beniculturali.it/cis>) VersionIRI(<http://dati.beniculturali.it/cis/3.2>))
```

E' l'unica cosa che dice quando si prova ad importare, quindi boh!? magari apro una issue sul [repository di protege](https://github.com/protegeproject/protege) giusto per chiuriosità.
Penso che a questo punto lo derubricherei come possibile baco di protege e penso che possiamo chiudere questa issue.

**Comment by giorgialodi** [comment]
Va bene Luigi, grazie mille per lo scambio :) Si scoprono sempre cose nuove!

**Comment by luigi-asprino** [comment]
ahahah.. si  a volte sono molto picky su cose assurde :-)
