### ISSUE TITLE
https://ontopia-virtuoso.agid.gov.it/sparql down

### ISSUE THREAD

**Issue by ecow** [italia/daf-ontologie-vocabolari-controllati#99]
A lot of links in the README are broken

**Comment by giorgialodi** [comment]
Yep, it depends on the title of this issue since all the single controlled vocabularies are visualized in HTML based on queries on the sparql endpoint. I tag @ioggstream who can contact people responsible in AGID for the maintenance of the SPARQL platform.

**Comment by mfortini** [comment]
@ioggstream can we close this?

**Comment by ecow** [comment]
yes for me

Il lun 27 set 2021, 19:40 Matteo Fortini ***@***.***> ha
scritto:
